=== krisling049/warcry_data/data/schemas/ability_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/data/schemas/ability_schema.json",
	"type": "object",
	"title": "Ability Schema",
	"required": [
		"_id",
		"name",
		"warband",
		"cost",
		"description",
		"runemarks"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this ability. In generated from the beginning of a uuid4.",
			"examples": [
				"c0fadcc5"
			]
		},
		"name": {
			"type": "string",
            "description": "Name of the ability",
            "examples": [
              "Grisly Trophy"
			]
		},
		"warband": {
			"type": "string",
			"description": "Name of the faction runemark on the ability, this may be a bladeborn warband",
			"examples": [
				"Garrek's Reavers", "Blades of Khorne: Bloodbound"
			]
		},
		"cost": {
			"type": "string",
			"description": "passive, reaction, double, triple or quad",
			"enum": [
				"passive",
    "reaction",
				"double",
				"triple",
				"quad"
			],
			"examples": [
				"double", "reaction"
			]
		},
		"description": {
			"type": "string",
			"description": "The rules text from the body of the ability. Ensure all quote marks are escaped correctly.",
			"examples": [
				"A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Until the end of the battle round, add 1 to the Attacks characteristic of melee attack actions made by visible friendly fighters while they are within 9\" of this fighter."
			]
		},
		"runemarks": {
			"type": "array",
			"default": [],
			"description": "Runemark names, lowercase. Do not include faction runemarks",
			"items": {
				"type": "string",
				"examples": [
					"destroyer"
				]
			}
		}
	},
	"examples": [
		{
			"_id": "c3c5056c",
			"name": "Grisly Trophy",
			"warband": "Corvus Cabal",
			"cost": "triple",
			"description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Until the end of the battle round, add 1 to the Attacks characteristic of melee attack actions made by visible friendly fighters while they are within 9\" of this fighter.",
			"runemarks": [
				"hero"
			]
		}
	]
}

=== krisling049/warcry_data/data/Chaos/hedonites_of_slaanesh_sybarites_abilities.json
[
    {
        "_id": "e20d873a",
        "name": "Dance of the Wailing Blade",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "double",
        "description": "Until the end of this fighter's activation, add 1 to the damage points allocated to enemy fighters by each hit and critical hit from melee attack actions made by this fighter.",
        "runemarks": [
            "warrior"
        ]
    },
    {
        "_id": "982a97f2",
        "name": "Slaves to Impulse",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "double",
        "description": "A fighter can only use this ability if there is a visible enemy fighter within 6\" of them. This fighter makes a bonus move action and must finish closer to the closest visible enemy fighter than they were at the start of that move action.",
        "runemarks": [
            "ferocious"
        ]
    },
    {
        "_id": "25ae4b3e",
        "name": "Unrivalled Velocity",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "double",
        "description": "Add 3 to this fighter's Move characteristic for their next move action in this activation.",
        "runemarks": []
    },
    {
        "_id": "96b6782c",
        "name": "Violence and Excess",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "double",
        "description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. This fighter makes a bonus move action or a bonus attack action.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "2e0f4291",
        "name": "Impaling Strike",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "triple",
        "description": "Until the end of this fighter's activation, the next time this fighter finishes a move action within 1\" of an enemy fighter, pick a visible enemy fighter within 1\" of this fighter. Allocate a number of damage points to that fighter equal to the value of this ability.",
        "runemarks": [
            "destroyer"
        ]
    },
    {
        "_id": "94ed80a4",
        "name": "Paragon of Depravity",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "quad",
        "description": "Until the end of the battle round, add the value of this ability to the Strength characteristic of melee attack actions made by visible friendly fighters while they are within 6\" of this fighter.",
        "runemarks": [
            "champion",
            "hero"
        ]
    },
    {
        "_id": "e7fd1214",
        "name": "Tendrils of Unnatural Smoke",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "triple",
        "description": "Until the end of the battle round, subtract 1 from the Attacks characteristic (to a minimum of 1) of attack actions made by enemy fighters while they are within 6\" of this fighter.",
        "runemarks": [
            "hero",
            "mystic"
        ]
    },
    {
        "_id": "260bfd0f",
        "name": "Volley of Tearing Blades",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "triple",
        "description": "Add 2 to the Attacks characteristic of the next missile attack action made by this fighter in this activation. In addition, add 1 to the Strength characteristic of that action while this fighter is within 3\" of a friendly fighter with the Hedonites of Slaanesh: Sybarites faction runemark and the Priest runemark.",
        "runemarks": [
            "minion"
        ]
    },
    {
        "_id": "a8b8d908",
        "name": "Ego-driven Excess",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "quad",
        "description": "This fighter can make a bonus move action or a bonus attack action. In addition, each time a fighter is taken down by an attack action made by this fighter this activation, this fighter can make a further bonus move action or bonus attack action.",
        "runemarks": [
            "berserker"
        ]
    },
    {
        "_id": "d9e17b86",
        "name": "Shared Pain",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "reaction",
        "description": "A fighter can make this reaction after they are targeted by a melee attack action but before the hit rolls are made. For each hit roll from that attack action that hits, allocate 1 damage point to the attacking fighter. For each critical hit, allocate 2 damage points to the attacking fighter instead.",
        "runemarks": []
    },
    {
        "_id": "d001e554",
        "name": " You First, I Insist",
        "warband": "Hedonites of Slaanesh: Sybarites",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 1\" of this fighter. That enemy fighter makes a bonus attack action targeting this fighter. Until the end of this f ighter's activation: \n- Add 2 to the Attacks and Strength characteristics of melee attack actions made by this fighter that target that enemy fighter. \n- Add 3 to the damage points allocated by each critical hit from melee attack actions made by this fighter that target that enemy fighter.",
        "runemarks": [
            "bulwark"
        ]
    },
    {
        "_id": "60eaf064",
        "name": "Cavalcade of Madness",
        "warband": "The Dread Pageant",
        "cost": "quad",
        "description": "This fighter makes a bonus attack action. In addition, if either this fighter or the target of the attack has any damage points allocated to them, add 1 to the Attacks characteristic of that bonus attack action. If both this fighter and the target fighter have any damage points allocated to them, add 3 to the Attacks characteristic of that bonus attack action instead.",
        "runemarks": []
    }
]

=== krisling049/warcry_data/data/order/stormcast_eternals_vanguard_auxiliary_chamber/stormcast_eternals_vanguard_auxiliary_chamber_abilities.json
[
    {
        "_id": "f0625e61",
        "name": "Lightning-fast Strikes",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "double",
        "description": "Add half the value of this ability (rounding up) to the Attacks characteristic of the next melee attack action made by this fighter this activation.",
        "runemarks": [
            "hero",
            "frenzied"
        ]
    },
    {
        "_id": "be5f2527",
        "name": "Righteous Aura",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "double",
        "description": "Until the end of the battle round, add 1 to the Toughness characteristic of friendly fighters while they are within 6\" of this fighter.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "c5955d4a",
        "name": "Tireless Hunters",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "double",
        "description": "Add 3 to this fighter's Move characteristic for their next move action in this activation.",
        "runemarks": []
    },
    {
        "_id": "fdd57def",
        "name": "Darting Attack",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "triple",
        "description": "This fighter makes a bonus attack action. Then, they can make a bonus disengage action.",
        "runemarks": [
            "beast"
        ]
    },
    {
        "_id": "7adc00f3",
        "name": "Rapid Fire",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "triple",
        "description": "Add 2 to the Attacks characteristic of the next missile attack action made by this fighter this activation.",
        "runemarks": [
            "bulwark"
        ]
    },
    {
        "_id": "86a90c64",
        "name": "Ride the Winds Aetheric",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "double",
        "description": "This fighter makes a bonus move action up to a number of inches equal to the value of this ability.",
        "runemarks": [
            "mount"
        ]
    },
    {
        "_id": "f57e8928",
        "name": "Star-fated Arrow",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "triple",
        "description": "Pick a visible enemy fighter within 20\" of this fighter and roll a dice. On a roll of 3-4, allocate 3 damage points to that fighter. On a roll of 5, allocate 6 damage points to that fighter. On a roll of 6, allocate 10 damage points to that fighter.",
        "runemarks": [
            "hero",
            "trapper"
        ]
    },
    {
        "_id": "fded2018",
        "name": "Aimed Strike",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "quad",
        "description": "Until the end of this fighter's activation, add the value of this ability to the damage points allocated to enemy fighters by each hit and critical hit from attack actions made by this fighter.",
        "runemarks": [
            "elite"
        ]
    },
    {
        "_id": "6908dc7d",
        "name": "The Light of Sigmar",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "quad",
        "description": "Allocate a number of damage points equal to the value of this ability to all visible enemy fighters within 3\" of this fighter.",
        "runemarks": [
            "hero",
            "berserker"
        ]
    },
    {
        "_id": "5b61673d",
        "name": "Warning Cry",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "reaction",
        "description": "A fighter can make this reaction after an enemy fighter finishes a move action visible to this fighter and within 6\" of this fighter. Until the end of the battle round, you can re-roll 1 dice during attack actions made by friendly fighters that target that fighter.",
        "runemarks": [
            "scout"
        ]
    },
    {
        "_id": "90f154cc",
        "name": "Thunderous Departure",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "reaction",
        "description": "A fighter can make this reaction when they are targeted by a melee attack action, after the damage is totalled but before it is allocated to this fighter, if it is enough for this fighter to be taken down. Allocate D6 damage points to their attacker. Fighters with the Beast runemark or both the Scout and Fly runemarks cannot make this reaction.",
        "runemarks": []
    },
    {
        "_id": "f29b1feb",
        "name": "Scions of the Storm",
        "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
        "cost": "battletrait",
        "description": "After deployment, you can pick a friendly fighter with this battle trait. If that fighter is on the battlefield, remove them from the battlefield. At the start of the second battle round onwards, starting with the attacker, you can place that fighter on the battlefield more than 5\" from each enemy fighter and more than 3\" from each objective and treasure token.",
        "runemarks": []
    },
    {
        "_id": "6a8cfa78",
        "name": "Guided by the Astral Compass",
        "warband": "The Farstriders",
        "cost": "triple",
        "description": "Each friendly fighter with the The Farstriders runemark within 6\" of this fighter when this fighter uses this ability can make a bonus move action.",
        "runemarks": [
            "hero"
        ]
    }
]

=== krisling049/warcry_data/data/Order/blacktalons_abilities.json
[
    {
        "_id": "af6705e7",
        "name": "Shield of Azyr",
        "warband": "Blacktalons",
        "cost": "reaction",
        "description": "A fighter can make this reaction after they are targeted by an attack action but before the hit rolls are made. Count up to two critical hits from that attack action as hits instead. If this fighter has the Hero runemark and is within 6\" of another friendly fighter with the Blacktalons runemark and the Champion or Destroyer runemark, count up to three critical hits from that attack action as hits instead.",
        "runemarks": []
    },
    {
        "_id": "f4925187",
        "name": "Storm of Justice",
        "warband": "Blacktalons",
        "cost": "double",
        "description": "Pick a visible friendly fighter with the Blacktalons runemark within a number of inches of this fighter equal to the value of this ability. That fighter makes a bonus move action or a bonus attack action.",
        "runemarks": [
            "champion"
        ]
    },
    {
        "_id": "cc2a11b5",
        "name": "Headshot",
        "warband": "Blacktalons",
        "cost": "triple",
        "description": "Add the value of this ability to the damage points allocated to enemy fighters by each hit and critical hit from the next ranged attack action made by this fighter in this activation.",
        "runemarks": [
            "destroyer"
        ]
    },
    {
        "_id": "ba962bd6",
        "name": "Nebulous Sea-fog",
        "warband": "Blacktalons",
        "cost": "triple",
        "description": "Until the end of the battle round, subtract 1 from the Attacks characteristic (to a minimum of 1) of attack actions made by enemy fighters while they are within 6\" of this fighter.",
        "runemarks": [
            "mystic"
        ]
    },
    {
        "_id": "a6ff68ea",
        "name": "Windrider",
        "warband": "Blacktalons",
        "cost": "quad",
        "description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Remove this fighter from the battlefield, then set this fighter up on a platform or the battlefield floor, more than 6\" from all enemy fighters. You can subtract the value of this ability from that 6\", to a minimum of 0.",
        "runemarks": [
            "hero"
        ]
    }
]

=== krisling049/warcry_data/data/Chaos/beasts_of_chaos_abilities.json
[
    {
        "_id": "f1a9eba3",
        "name": "Bloodgorge",
        "warband": "Beasts of Chaos",
        "cost": "double",
        "description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Remove a number of damage points allocated to this fighter up to the value of this ability.",
        "runemarks": [
            "brute"
        ]
    },
    {
        "_id": "1c42f884",
        "name": "Brayherd Ambush",
        "warband": "Beasts of Chaos",
        "cost": "double",
        "description": "A fighter can only use this ability if it is the first battle round. This fighter can make a bonus move action up to a number of inches equal to the value of this ability.",
        "runemarks": []
    },
    {
        "_id": "d6bef6fd",
        "name": "Devolve",
        "warband": "Beasts of Chaos",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 6\" of this fighter. That enemy fighter makes a bonus move action directly towards this fighter, as if they were jumping, a number of inches equal to the value of this ability. When doing so, they can move away from enemy fighters within 1\" at the start of that move action.",
        "runemarks": [
            "hero",
            "mystic"
        ]
    },
    {
        "_id": "33c7d45b",
        "name": "Rip, Gore and Tear!",
        "warband": "Beasts of Chaos",
        "cost": "double",
        "description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. This fighter makes a bonus move action or a bonus attack action.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "1f49c5fc",
        "name": "Bestial Charge",
        "warband": "Beasts of Chaos",
        "cost": "triple",
        "description": "Until the end of this fighter's activation, the next time this fighter finishes a move action within 1\" of an enemy fighter, pick a visible enemy fighter within 1\" of this fighter. Allocate a number of damage points to that fighter equal to the value of this ability.",
        "runemarks": [
            "warrior"
        ]
    },
    {
        "_id": "9f714195",
        "name": "Grisly Trophy",
        "warband": "Beasts of Chaos",
        "cost": "triple",
        "description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Until the end of the battle round, add 1 to the Attacks characteristic of melee attack actions made by visible friendly fighters while they are within 9\" of this fighter.",
        "runemarks": [
            "hero",
            "champion"
        ]
    },
    {
        "_id": "9d2b4844",
        "name": "Petrifying Gaze",
        "warband": "Beasts of Chaos",
        "cost": "triple",
        "description": "Pick a visible enemy fighter within 8\" of this fighter and roll a dice. On a roll of 2+, allocate a number of damage points to that fighter equal to the roll. In addition, until the end of the battle round, subtract 1 from the Move characteristic of that fighter (to a minimum of 1).",
        "runemarks": [
            "berserker"
        ]
    },
    {
        "_id": "b406c9c6",
        "name": "Volley of Arrows",
        "warband": "Beasts of Chaos",
        "cost": "triple",
        "description": "Add half the value of this ability (rounding up) to the Attacks characteristic of the next missile attack action made by this fighter in this activation.",
        "runemarks": [
            "scout"
        ]
    },
    {
        "_id": "6e95ab56",
        "name": "Bring Down the Storm",
        "warband": "Beasts of Chaos",
        "cost": "triple",
        "description": "Pick a visible enemy fighter within 20\" of this fighter and roll a dice. On a roll of 2+, allocate a number of damage points to that fighter equal to the value of this ability.",
        "runemarks": [
            "destroyer"
        ]
    },
    {
        "_id": "f1cade78",
        "name": "Empowering Lightning",
        "warband": "Beasts of Chaos",
        "cost": "quad",
        "description": "Remove a number of damage points up to the value of this ability allocated to each friendly fighter with both the Beasts of Chaos faction runemark and the Destroyer runemark within 9\" of this fighter.",
        "runemarks": [
            "hero",
            "destroyer"
        ]
    },
    {
        "_id": "8e6dc5a6",
        "name": "Brute Resilience",
        "warband": "Beasts of Chaos",
        "cost": "reaction",
        "description": "A fighter can make this reaction when they are targeted by a melee attack action but before the hit rolls are made. Subtract 1 from the damage points allocated to this fighter by each hit from that attack action (to a minimum of 1).",
        "runemarks": []
    },
    {
        "_id": "fbce3d1d",
        "name": "Savage Bolt",
        "warband": "Grashrak's Despoilers",
        "cost": "quad",
        "description": "Pick a visible enemy fighter within 12\" of this fighter.  Allocate a number of damage points to that fighter equal to the value of this ability. Then, roll a die. On a 2+, that fighter cannot activate this round.",
        "runemarks": [
            "hero"
        ]
    }
]
