=== krisling049/warcry_data/data/schemas/ability_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/data/schemas/ability_schema.json",
	"type": "object",
	"title": "Ability Schema",
	"required": [
		"_id",
		"name",
		"warband",
		"cost",
		"description",
		"runemarks"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this ability. In generated from the beginning of a uuid4.",
			"examples": [
				"c0fadcc5"
			]
		},
		"name": {
			"type": "string",
            "description": "Name of the ability",
            "examples": [
              "Grisly Trophy"
			]
		},
		"warband": {
			"type": "string",
			"description": "Name of the faction runemark on the ability, this may be a bladeborn warband",
			"examples": [
				"Garrek's Reavers", "Blades of Khorne: Bloodbound"
			]
		},
		"cost": {
			"type": "string",
			"description": "passive, reaction, double, triple or quad",
			"enum": [
				"passive",
    "reaction",
				"double",
				"triple",
				"quad"
			],
			"examples": [
				"double", "reaction"
			]
		},
		"description": {
			"type": "string",
			"description": "The rules text from the body of the ability. Ensure all quote marks are escaped correctly.",
			"examples": [
				"A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Until the end of the battle round, add 1 to the Attacks characteristic of melee attack actions made by visible friendly fighters while they are within 9\" of this fighter."
			]
		},
		"runemarks": {
			"type": "array",
			"default": [],
			"description": "Runemark names, lowercase. Do not include faction runemarks",
			"items": {
				"type": "string",
				"examples": [
					"destroyer"
				]
			}
		}
	},
	"examples": [
		{
			"_id": "c3c5056c",
			"name": "Grisly Trophy",
			"warband": "Corvus Cabal",
			"cost": "triple",
			"description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Until the end of the battle round, add 1 to the Attacks characteristic of melee attack actions made by visible friendly fighters while they are within 9\" of this fighter.",
			"runemarks": [
				"hero"
			]
		}
	]
}

=== krisling049/warcry_data/data/order/daughters_of_khaine/daughters_of_khaine_abilities.json
[
    {
        "_id": "879f9846",
        "name": "Bathe In Blood",
        "warband": "Daughters of Khaine",
        "cost": "double",
        "description": "A fighter can only use this ability if they are within 3\" of a visible enemy fighter with 1 or more damage points allocated to them. Until the end of this fighter's activation, add 1 to the Attacks and Strength characteristics of melee attack actions made by this fighter.",
        "runemarks": []
    },
    {
        "_id": "1d8101c7",
        "name": "Killing Stroke",
        "warband": "Daughters of Khaine",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 1\" of this fighter and roll a dice. On a roll of 3+, allocate 3 damage points to that fighter.",
        "runemarks": [
            "trapper",
            "hero"
        ]
    },
    {
        "_id": "1ea8e8d5",
        "name": "Turned to Crystal",
        "warband": "Daughters of Khaine",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 6\" of this fighter and roll 2 dice. For each roll of 4-5, allocate 1 damage point to that fighter. For each roll of 6, allocate a number of damage points to that fighter equal to the value of this ability.",
        "runemarks": [
            "elite"
        ]
    },
    {
        "_id": "971edd8f",
        "name": "Witchbrew",
        "warband": "Daughters of Khaine",
        "cost": "double",
        "description": "Pick a visible friendly fighter within 3\" of this fighter. Until the end of the battle round, add the value of this ability to the Strength characteristic of the next melee attack action made by that fighter.",
        "runemarks": [
            "priest",
            "hero"
        ]
    },
    {
        "_id": "27ef2336",
        "name": "Bloodwrack Stare",
        "warband": "Daughters of Khaine",
        "cost": "triple",
        "description": "Pick a visible enemy fighter within a number of inches of this fighter equal to the value of this ability and roll 2 dice. If either dice rolls a 3+, until the end of the battle round, that fighter cannot make move actions or disengage actions. In addition, for each roll of 6, allocate a number of damage points to that fighter equal to the value of this ability.",
        "runemarks": [
            "mystic",
            "hero"
        ]
    },
    {
        "_id": "dd4d59b4",
        "name": "Doomfire Bolt",
        "warband": "Daughters of Khaine",
        "cost": "triple",
        "description": "Pick a visible enemy fighter within 9\" of this fighter and roll a number of dice equal to the value of this ability. For each roll of 4+, allocate 2 damage points to that fighter.",
        "runemarks": [
            "mount"
        ]
    },
    {
        "_id": "f40299bf",
        "name": "Heartseekers",
        "warband": "Daughters of Khaine",
        "cost": "triple",
        "description": "After the next missile attack action made by this fighter in this activation, if it scored one or more hits, allocate a number of damage points to the target of that attack action equal to the value of this ability.",
        "runemarks": [
            "berserker"
        ]
    },
    {
        "_id": "b87b3267",
        "name": "Sacrifice to Khaine",
        "warband": "Daughters of Khaine",
        "cost": "triple",
        "description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Until the end of the battle round, add 1 to the Attacks characteristic of melee attack actions made by visible friendly fighters while they are within 6\" of this fighter.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "26f66ad2",
        "name": "Slaughter's Strength",
        "warband": "Daughters of Khaine",
        "cost": "triple",
        "description": "Until the end of this fighter's activation, add half the value of this ability (rounding up) to the Strength characteristic of melee attack actions made by this fighter.",
        "runemarks": []
    },
    {
        "_id": "ce7caf2f",
        "name": "Death on the Wind",
        "warband": "Daughters of Khaine",
        "cost": "quad",
        "description": "This fighter makes a bonus move action. Then, they can make a bonus attack action. Add 1 to the Strength characteristic of that attack action if the fighter finished the move action 6\" or more from their starting position.",
        "runemarks": [
            "agile"
        ]
    },
    {
        "_id": "55556335",
        "name": "Orgy of Slaughter",
        "warband": "Daughters of Khaine",
        "cost": "quad",
        "description": "Until the end of the battle round, add half the value of this ability (rounding up) to the damage points allocated to enemy fighters by each critical hit from melee attack actions made by friendly fighters while they are within 8\" of this fighter.",
        "runemarks": [
            "destroyer",
            "hero"
        ]
    },
    {
        "_id": "4e213d1d",
        "name": "Gladiatorial Display",
        "warband": "Daughters of Khaine",
        "cost": "reaction",
        "description": "A fighter can make this reaction after they are targeted by a melee attack action but before the hit rolls are made. If none of the hit rolls from that attack action result in a critical hit, allocate 4 damage points to the attacking fighter.",
        "runemarks": []
    },
    {
        "_id": "634e3c1f",
        "name": "Jubilant Bloodletting",
        "warband": "Daughters of Khaine",
        "cost": "battletrait",
        "description": "When a friendly fighter with this battle trait makes a melee attack action, after the hit rolls have been made, if you scored one or more critical hits and one or more hits and/or critical hits, you can pick a [double], [triple], or [quad] you have. Add 2 to the value of that ability dice, to a maximum of 6.",
        "runemarks": []
    },
    {
        "_id": "2c353eb1",
        "name": "Peerless Combatant",
        "warband": "Gryselle's Arenai",
        "cost": "double",
        "description": "Until the end of this fighter's activation, damage cannot be allocated to this fighter by enemy fighters' reactions.",
        "runemarks": []
    },
    {
        "_id": "b3047b15",
        "name": "Combination Attack",
        "warband": "Gryselle's Arenai",
        "cost": "triple",
        "description": "A fighter can only use this ability if an enemy fighter has been allocated damage by a melee attack action made by them this activation.  This fighter makes a bonus melee attack action that targets that enemy fighter.",
        "runemarks": []
    },
    {
        "_id": "be42bda3",
        "name": "Marshal the Bladestorm",
        "warband": "Gryselle's Arenai",
        "cost": "triple",
        "description": "Until the end of the battle round, add 1 to the Toughness characteristic of friendly fighters with the Gryselle's Arenai runemark while they are within 6\" of this fighter.",
        "runemarks": []
    },
    {
        "_id": "b3eb52dd",
        "name": "Acrobatic Display",
        "warband": "Gryselle's Arenai",
        "cost": "reaction",
        "description": "A fighter can make this reaction when they are targeted by an attack action but before the hit rolls are made. Subtract 1 from the damage points allocated to this fighter by each hit from that attack action (to a minimum of 1).",
        "runemarks": []
    },
    {
        "_id": "98ece5ab",
        "name": "Daughters of the First Temple",
        "warband": "Morgwaeth's Blade-Coven",
        "cost": "double",
        "description": "Pick another visible friendly fighter with the Morgwaeth's blade-Coven runemark within 3\" of this fighter. That fighter can make a bonus attack action.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "ab45a9bd",
        "name": "Slip Between Shadows",
        "warband": "The Shadeborn",
        "cost": "reaction",
        "description": "A fighter can make this reaction when an enemy fighter finishes a move action within 3\" of them. Note the distance between this fighter and the enemy fighter that made the move action. Remove this fighter from the battlefield, then set this fighter up on a platform or the battlefield floor, no further from the enemy fighter that made the move action.",
        "runemarks": []
    },
    {
        "_id": "3b009c24",
        "name": "Shadestalker Darts",
        "warband": "The Shadeborn",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 6\" of this fighter and roll 2 dice. For each roll of 4-5, allocate 2 damage points to that fighter. For each roll of 6, allocate a number of damage points to that fighter equal to the value of this ability (minimum 2).",
        "runemarks": []
    },
    {
        "_id": "2c3fa72f",
        "name": "Gloomweb Hex",
        "warband": "The Shadeborn",
        "cost": "triple",
        "description": "Pick an enemy fighter within 6\" of this fighter. Subtract half of the value of this ability (rounding up) from the Attacks characteristic (to a minimum of 1) attack actions made by that fighter until the end of the battle round.",
        "runemarks": [
            "trapper"
        ]
    },
    {
        "_id": "e3a5da77",
        "name": "Shadow Ambush",
        "warband": "The Shadeborn",
        "cost": "quad",
        "description": "Remove this fighter from the battlefield and then immediately set them up anywhere on the battlefield.",
        "runemarks": [
            "hero"
        ]
    }
]

=== krisling049/warcry_data/data/Order/hunters_of_huanchi_abilities.json
[
    {
        "_id": "0b3e0162",
        "name": "Agile Climbers",
        "warband": "Hunters of Huanchi",
        "cost": "double",
        "description": "Until the end of this fighter's activation, do not count the vertical distance moved when this fighter is climbing.",
        "runemarks": [
            "agile"
        ]
    },
    {
        "_id": "0bb29a64",
        "name": "Envenomed Weapons",
        "warband": "Hunters of Huanchi",
        "cost": "double",
        "description": "Add 1 to the damage points allocated by each hit and critical hit from the next attack action made by this fighter this activation.",
        "runemarks": [
            "agile"
        ]
    },
    {
        "_id": "50fdb642",
        "name": "Hurled Bolas",
        "warband": "Hunters of Huanchi",
        "cost": "triple",
        "description": "Pick a visible enemy fighter within 8\" of this fighter and roll a number of dice equal to the value of this ability.  If 1 of the dice scores a 6, that fighter makes 1 fewer action in this battle round (to a minimum of 0).  If a fighter is reduced to 0 actions in this way, that fighter cannot be activated in this battle round.",
        "runemarks": [
            "trapper"
        ]
    },
    {
        "_id": "642e57d4",
        "name": "Bellow of the Carnosaur",
        "warband": "Hunters of Huanchi",
        "cost": "triple",
        "description": "Pick an enemy fighter within 6\" of this fighter.  Until the end of the battle round, subtract 1 from the Move characteristic of that fighter (to a minimum of 1) and subtract 1 from the damage points allocated by each hit and critical hit from attack actions made by that fighter (to a minimum of 1).",
        "runemarks": [
            "icon-bearer"
        ]
    },
    {
        "_id": "fac6ce44",
        "name": "Call of the Hunt",
        "warband": "Hunters of Huanchi",
        "cost": "triple",
        "description": "Pick a friendly fighter with the Hunters of Huanchi and Beast runemarks within 9\" of this fighter.  That fighter makes a bonus move action.  Then pick a visible enemy fighter within 1\" of the fighter that made the bonus move action and allocate a number of damage points to that fighter equal to the value of this ability.",
        "runemarks": [
            "scout"
        ]
    },
    {
        "_id": "08b62c60",
        "name": "Hit and Run",
        "warband": "Hunters of Huanchi",
        "cost": "quad",
        "description": "This fighter makes a bonus move action or a bonus disengage action, then this fighter makes a bonus attack action or a bonus move action.",
        "runemarks": [
            "agile"
        ]
    },
    {
        "_id": "133bc02c",
        "name": "Slippery",
        "warband": "Hunters of Huanchi",
        "cost": "reaction",
        "description": "A fighter can make this reaction after they have been allocated the total damage points by a melee attack action. This fighter makes a bonus disengage action.",
        "runemarks": [
            "agile"
        ]
    },
    {
        "_id": "257f7546",
        "name": "Hidden Hunters",
        "warband": "Hunters of Huanchi",
        "cost": "battletrait",
        "description": "After deployment, each player whose warband has this battle trait can pick a friendly fighter with this battle trait from each friendly battle group that is on the battlefield. One at a time, remove those fighters from the battlefield and pick a different battle group. Then deploy that fighter as if it were part of that battle group.",
        "runemarks": []
    }
]

=== krisling049/warcry_data/data/Chaos/maggotkin_of_nurgle_daemons_abilities.json
[
    {
        "_id": "d1c3e90e",
        "name": "Acidic Slime Trail",
        "warband": "Maggotkin of Nurgle: Daemons",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 1\" of this fighter. This fighter makes a bonus disengage action. Then, allocate a number of damage points to that fighter equal to the value of this ability.",
        "runemarks": [
            "ferocious"
        ]
    },
    {
        "_id": "7b88e541",
        "name": "Jolly Gutpipes",
        "warband": "Maggotkin of Nurgle: Daemons",
        "cost": "double",
        "description": "Until the end of the battle round, add 1 to the Move characteristic of friendly fighters while they make a move action that starts within 7\" of this fighter.",
        "runemarks": [
            "hero",
            "agile"
        ]
    },
    {
        "_id": "36191fb0",
        "name": "Disgustingly Resilient",
        "warband": "Maggotkin of Nurgle: Daemons",
        "cost": "double",
        "description": "Roll a number of dice equal to the value of this ability. For each roll of 3+, remove up to 1 damage point allocated to this fighter.",
        "runemarks": []
    },
    {
        "_id": "e4fcbd83",
        "name": "Venomous Sting",
        "warband": "Maggotkin of Nurgle: Daemons",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 1\" of this fighter and roll a dice. On a roll of 2+, until the end of this battle round, that fighter cannot make move actions or disengage actions.",
        "runemarks": [
            "destroyer"
        ]
    },
    {
        "_id": "4ba7bd21",
        "name": "Cloud of Flies",
        "warband": "Maggotkin of Nurgle: Daemons",
        "cost": "triple",
        "description": "Until the end of the battle round, subtract 1 from the Attacks characteristic (to a minimum of 1) of attack actions that target this fighter.",
        "runemarks": [
            "warrior"
        ]
    },
    {
        "_id": "9efb5761",
        "name": "Grandfather's Blessing",
        "warband": "Maggotkin of Nurgle: Daemons",
        "cost": "triple",
        "description": "Until the end of the battle round, add 1 to the Strength characteristic of melee attack actions made by visible friendly fighters while they are within 7\" of this fighter.",
        "runemarks": [
            "hero",
            "champion"
        ]
    },
    {
        "_id": "eb4c8d1f",
        "name": "Menacing Overseer",
        "warband": "Maggotkin of Nurgle: Daemons",
        "cost": "quad",
        "description": "Until the end of the battle round, add 1 to the Attacks characteristic of melee attack actions made by visible friendly fighters while they are within 9\" of this fighter.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "bc938e66",
        "name": "Disgusting Sneeze",
        "warband": "Maggotkin of Nurgle: Daemons",
        "cost": "triple",
        "description": "Pick a visible enemy fighter within 7\" of this fighter and roll a number of dice equal to the value of this ability. For each roll of 2+, allocate 1 damage point to that fighter.",
        "runemarks": [
            "hero",
            "champion"
        ]
    },
    {
        "_id": "26f3ceec",
        "name": "Endless Swarm",
        "warband": "Maggotkin of Nurgle: Daemons",
        "cost": "quad",
        "description": "Remove a number of damage points allocated to this fighter up to double the value of this ability.",
        "runemarks": [
            "minion"
        ]
    },
    {
        "_id": "7c142afa",
        "name": "Impossible to Wound",
        "warband": "Maggotkin of Nurgle: Daemons",
        "cost": "reaction",
        "description": "A fighter can make this reaction when they are targeted by a melee attack action but before the hit rolls are made. Subtract 1 from the damage points allocated to this fighter by each hit from that attack action (to a minimum of 1).",
        "runemarks": []
    }
]

=== krisling049/warcry_data/data/Chaos/untamed_beasts_abilities.json
[
    {
        "_id": "eb8fdbfa",
        "name": "All-out Attack",
        "warband": "Untamed Beasts",
        "cost": "double",
        "description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. This fighter makes a bonus move action or a bonus attack action.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "7609f611",
        "name": "Beastmaster",
        "warband": "Untamed Beasts",
        "cost": "double",
        "description": "Pick a visible friendly fighter with the Beast runemark within 4\" of this fighter. That fighter makes a bonus attack action.",
        "runemarks": [
            "agile"
        ]
    },
    {
        "_id": "d6b28f28",
        "name": "Savage Fury",
        "warband": "Untamed Beasts",
        "cost": "double",
        "description": "Add 1 to the Move characteristic of this fighter for the next move action they make in this activation, and add 1 to the Attacks characteristic of the next attack action made by this fighter in this activation.",
        "runemarks": []
    },
    {
        "_id": "eef17740",
        "name": "Harpoon Snag",
        "warband": "Untamed Beasts",
        "cost": "triple",
        "description": "This fighter makes a bonus attack action. After that attack action, the target of that attack action makes a bonus move action directly towards this fighter, as if they were jumping, a number of inches equal to the value of this ability. When doing so, they can move away from enemy fighters within 1\" at the start of that move action.",
        "runemarks": [
            "brute"
        ]
    },
    {
        "_id": "69024f7c",
        "name": "Pounce",
        "warband": "Untamed Beasts",
        "cost": "triple",
        "description": "Until the end of this fighter's activation, the next time this fighter finishes a move action within 1\" of an enemy fighter, pick a visible enemy fighter within 1\" of this fighter. Allocate a number of damage points to that fighter equal to the value of this ability.",
        "runemarks": [
            "beast"
        ]
    },
    {
        "_id": "6754dbc8",
        "name": "Unleash the Beast",
        "warband": "Untamed Beasts",
        "cost": "quad",
        "description": "Until the end of the battle round, add half the value of this ability (rounding up) to the Attacks and Strength characteristics of melee attack actions made by this fighter.",
        "runemarks": []
    },
    {
        "_id": "836b5da8",
        "name": "Brute Resilience",
        "warband": "Untamed Beasts",
        "cost": "reaction",
        "description": "A fighter can make this reaction when they are targeted by a melee attack action but before the hit rolls are made. Subtract 1 from the damage points allocated to this fighter by each hit from that attack action (to a minimum of 1).",
        "runemarks": []
    },
    {
        "_id": "7ead189d",
        "name": "Worthy Prey",
        "warband": "Untamed Beasts",
        "cost": "battletrait",
        "description": "At the start of each battle round, if no enemy fighters are your worthy prey, pick an enemy fighter. That fighter is your worth prey. While that fighter is your worthy prey, abilities that target that fighter are treated as having a value of 6.",
        "runemarks": []
    }
]

=== krisling049/warcry_data/data/destruction/gorger_mawpack/gorger_mawpack_abilities.json
[
    {
        "_id": "e3ae1ed5",
        "name": "Rending Bite",
        "warband": "Gorger Mawpack",
        "cost": "reaction",
        "description": "A fighter can make this reaction after they are targeted by a melee attack action but before the hit rolls are made. If none of the hit rolls from that attack action result in a critical hit, allocate 6 damage points to the attacking fighter.",
        "runemarks": []
    },
    {
        "_id": "cab60322",
        "name": "Bounding Leaps",
        "warband": "Gorger Mawpack",
        "cost": "double",
        "description": "A fighter can only use this ability if there is a visible enemy fighter within 6\" of them. This fighter makes a bonus move action and must finish closer to the closest visible enemy fighter than they were at the start of that move action.",
        "runemarks": []
    },
    {
        "_id": "6a45bb85",
        "name": "Glimmer of Consciousness",
        "warband": "Gorger Mawpack",
        "cost": "double",
        "description": "Until the start of the next battle round, this fighter is not considered to have the Beast  runemark. If this fighter is carrying treasure at the start of the next battle round, it drops that treasure.",
        "runemarks": [
            "beast"
        ]
    },
    {
        "_id": "bfae953f",
        "name": "Unnatural Force",
        "warband": "Gorger Mawpack",
        "cost": "double",
        "description": "Until the end of this fighter's activation, add 1 to the damage points allocated to enemy fighters by each hit and critical hit from melee attack actions made by this fighter.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "bebbf0d1",
        "name": "Agonising Roar",
        "warband": "Gorger Mawpack",
        "cost": "triple",
        "description": "Roll a dice for each enemy fighter within 6\" of this fighter. On a roll of 4+, until the end of the battle round, the fighter being rolled for cannot make disengage actions.",
        "runemarks": [
            "berserker"
        ]
    },
    {
        "_id": "2cedb53d",
        "name": "Maddened Blows",
        "warband": "Gorger Mawpack",
        "cost": "triple",
        "description": "Until the end of this fighter's activation, hit rolls for attack actions made by this fighter score a critical hit on a roll of 5+.",
        "runemarks": [
            "destroyer"
        ]
    },
    {
        "_id": "1d3da6e3",
        "name": "Starving Rampage",
        "warband": "Gorger Mawpack",
        "cost": "quad",
        "description": "Until the end of the battle round, this fighter is considered to have the Beast runemark. If this fighter is carrying treasure, they drop that treasure. This fighter can make 1 bonus melee attack action for each visible enemy fighter within 1\" of them. Each of these attack actions must target a different fighter.",
        "runemarks": []
    },
    {
        "_id": "2e2fb526",
        "name": "Ravenous Gorging",
        "warband": "Gorger Mawpack",
        "cost": "battletrait",
        "description": "After an enemy fighter has been taken down by a melee attack action made by a friendly fighter with this battle trait, remove D3 damage points allocated to that friendly fighter.",
        "runemarks": []
    }
]
