=== krisling049/warcry_data/data/schemas/ability_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/data/schemas/ability_schema.json",
	"type": "object",
	"title": "Ability Schema",
	"required": [
		"_id",
		"name",
		"warband",
		"cost",
		"description",
		"runemarks"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this ability. In generated from the beginning of a uuid4.",
			"examples": [
				"c0fadcc5"
			]
		},
		"name": {
			"type": "string",
            "description": "Name of the ability",
            "examples": [
              "Grisly Trophy"
			]
		},
		"warband": {
			"type": "string",
			"description": "Name of the faction runemark on the ability, this may be a bladeborn warband",
			"examples": [
				"Garrek's Reavers", "Blades of Khorne: Bloodbound"
			]
		},
		"cost": {
			"type": "string",
			"description": "passive, reaction, double, triple or quad",
			"enum": [
				"passive",
    "reaction",
				"double",
				"triple",
				"quad"
			],
			"examples": [
				"double", "reaction"
			]
		},
		"description": {
			"type": "string",
			"description": "The rules text from the body of the ability. Ensure all quote marks are escaped correctly.",
			"examples": [
				"A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Until the end of the battle round, add 1 to the Attacks characteristic of melee attack actions made by visible friendly fighters while they are within 9\" of this fighter."
			]
		},
		"runemarks": {
			"type": "array",
			"default": [],
			"description": "Runemark names, lowercase. Do not include faction runemarks",
			"items": {
				"type": "string",
				"examples": [
					"destroyer"
				]
			}
		}
	},
	"examples": [
		{
			"_id": "c3c5056c",
			"name": "Grisly Trophy",
			"warband": "Corvus Cabal",
			"cost": "triple",
			"description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Until the end of the battle round, add 1 to the Attacks characteristic of melee attack actions made by visible friendly fighters while they are within 9\" of this fighter.",
			"runemarks": [
				"hero"
			]
		}
	]
}

=== krisling049/warcry_data/data/order/idoneth_deepkin/idoneth_deepkin_abilities.json
[
    {
        "_id": "6d695b7a",
        "name": "Ink Jet",
        "warband": "Cyreni's Razors",
        "cost": "reaction",
        "description": "A fighter can make this reaction after they are targeted by a melee attack action but before the hit rolls are made. For each hit roll from that attack action that misses, after that attack action is resolved, you can move this fighter up to 2\". In addition, if all of the hit rolls missed, that enemy fighter cannot make attack actions until the end of the battle round.",
        "runemarks": [
            "beast"
        ]
    },
    {
        "_id": "7479b3ed",
        "name": "Hurl Lanmari Blade",
        "warband": "Cyreni's Razors",
        "cost": "double",
        "description": "Add the value of this ability to the Range characteristic of the next melee attack action made by this fighter this activation. After that attack action, this fighter cannot make melee attack actions for the rest of this activation.",
        "runemarks": [
            "minion"
        ]
    },
    {
        "_id": "06b33bb6",
        "name": "Hammertide",
        "warband": "Cyreni's Razors",
        "cost": "triple",
        "description": "Pick a corner of the battlefield and draw a straight line 1mm wide between the centre of this fighter's base and that corner. Enemy fighters whose base touches that line cannot jump, fly or climb until the end of this battle round. In addition, roll a number of dice equal to the value of this ability for each such enemy fighter. Allocate 1 damage point to that fighter for each roll of 3+.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "c5c07e49",
        "name": "Crushing Wrap",
        "warband": "Cyreni's Razors",
        "cost": "quad",
        "description": "A fighter can only use this ability before it would make a melee attack action. Roll 8 dice. For each roll of 3+, add 1 to this fighter's Strength characteristic for that attack action and allocate 2 damage points to the target of that attack action. If the target is taken out of action, the melee attack action has no effect.",
        "runemarks": [
            "beast"
        ]
    },
    {
        "_id": "efc50c98",
        "name": "Soulnet",
        "warband": "Elathain's Soulraid",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 3\" of this fighter and roll a dice.  On a 3+, that fighter cannot make move actions or disengage actions until the end of the battle round.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "f5bce2eb",
        "name": "Riptide Harpoon",
        "warband": "Elathain's Soulraid",
        "cost": "triple",
        "description": "This fighter makes a bonus attack action.  After that attack action, the fighter targeted by that attack action makes a bonus move action directly towards this figther, as if they were jumping, a number of inches equal to the value of this ability.",
        "runemarks": [
            "trapper"
        ]
    },
    {
        "_id": "7c49099a",
        "name": "Hangman's Knot",
        "warband": "Idoneth Deepkin",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 3\" of this fighter and roll a dice. On a roll of 3+, until the end of the battle round, that fighter cannot make move actions or disengage actions.",
        "runemarks": [
            "hero",
            "frenzied"
        ]
    },
    {
        "_id": "10f4fc28",
        "name": "Low Tide",
        "warband": "Idoneth Deepkin",
        "cost": "double",
        "description": "A fighter can use this ability only if it is the first battle round. This fighter can make a bonus move action up to a number of inches equal to the value of this ability.",
        "runemarks": []
    },
    {
        "_id": "fe0cb3c3",
        "name": "Riptide",
        "warband": "Idoneth Deepkin",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 12\" of this fighter. Until the end of the battle round, subtract 1 from the Attacks characteristic (to a minimum of 1) of attack actions made by that fighter.",
        "runemarks": [
            "hero",
            "mystic"
        ]
    },
    {
        "_id": "e9d22c1c",
        "name": "Storm Fire",
        "warband": "Idoneth Deepkin",
        "cost": "double",
        "description": "Until the end of this fighter's activation, add 1 to the Attacks characteristic of missile attack actions made by this fighter.",
        "runemarks": [
            "agile"
        ]
    },
    {
        "_id": "f498473c",
        "name": "Storm of Blows",
        "warband": "Idoneth Deepkin",
        "cost": "double",
        "description": "Add half the value of this ability (rounding up) to the Attacks characteristic of the next melee attack action made by this fighter in this activation.",
        "runemarks": [
            "hero",
            "champion"
        ]
    },
    {
        "_id": "094f07e8",
        "name": "Sweeping Blow",
        "warband": "Idoneth Deepkin",
        "cost": "double",
        "description": "Roll a dice for each visible enemy fighter within 2\" of this fighter. On a roll of 5, allocate 1 damage point to the fighter being rolled for. On a roll of 6, allocate a number of damage points to the fighter being rolled for equal to the value of this ability.",
        "runemarks": [
            "minion"
        ]
    },
    {
        "_id": "60bba3cb",
        "name": "Biovoltaic Barrier",
        "warband": "Idoneth Deepkin",
        "cost": "triple",
        "description": "Until the end of the battle round, count each critical hit from attack actions that target this fighter as a hit instead.",
        "runemarks": [
            "bulwark"
        ]
    },
    {
        "_id": "be1c62dd",
        "name": "High Tide",
        "warband": "Idoneth Deepkin",
        "cost": "triple",
        "description": "A fighter can only use this ability if it is the third battle round. Add 1 to the Attacks and Strength characteristics of melee attack actions made by friendly fighters while they are within 6\" of this fighter.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "997d8ddd",
        "name": "Scryfish Shoal",
        "warband": "Idoneth Deepkin",
        "cost": "triple",
        "description": "Pick a visible enemy fighter within 10\" of this fighter and roll 6 dice. For each roll of 4-5, allocate 1 damage point to that fighter. For each roll of 6, allocate 2 damage points to that fighter.",
        "runemarks": [
            "hero",
            "priest"
        ]
    },
    {
        "_id": "4d837d86",
        "name": "Way of the Depths",
        "warband": "Idoneth Deepkin",
        "cost": "triple",
        "description": "Until the end of the battle round, add 1 to the Strength characteristic of melee attack actions made by this fighter and by visible friendly fighters with the Idoneth Deepkin faction runemark and either the Agile or Minion runemarks while they are within 6\" of this fighter.",
        "runemarks": [
            "hero",
            "sentience"
        ]
    },
    {
        "_id": "190ec318",
        "name": "Biovoltaic Blast",
        "warband": "Idoneth Deepkin",
        "cost": "quad",
        "description": "Allocate a number of damage points equal to the value of this ability to all visible enemy fighters within 3\" of this fighter.",
        "runemarks": [
            "berserker"
        ]
    },
    {
        "_id": "f76c0a5e",
        "name": "Fade from Memory",
        "warband": "Idoneth Deepkin",
        "cost": "reaction",
        "description": "A fighter can make this reaction when an enemy fighter finishes a move action within 3\" of them. If there is another friendly fighter visible to that enemy fighter and within range of at least one of that enemy fighter's melee weapons, for the rest of the battle round that enemy fighter cannot target this fighter.",
        "runemarks": []
    },
    {
        "_id": "f9e19991",
        "name": "Power of the Tides",
        "warband": "Idoneth Deepkin",
        "cost": "battletrait",
        "description": "In battle rounds 1 and 2, add 1 to the Move characteristic of friendly fighters with this battle trait. In battle rounds 3 and 4, add 1 to the Strength characteristic of melee attack actions made by friendly fighters with the battle trait.",
        "runemarks": []
    }
]

=== krisling049/warcry_data/data/Chaos/corvus_cabal_abilities.json
[
    {
        "_id": "db4552ec",
        "name": "Harrying Raven",
        "warband": "Corvus Cabal",
        "cost": "double",
        "description": "Pick an enemy fighter within 20\" of this fighter. Until the end of the battle round, that fighter cannot make disengage actions.",
        "runemarks": [
            "scout"
        ]
    },
    {
        "_id": "26c85cff",
        "name": "Raven Dart",
        "warband": "Corvus Cabal",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 8\" of this fighter and roll a dice. On a roll of 2-4, allocate 1 damage point to that fighter. On a roll of 5+, allocate a number of damage points to that fighter equal to the value of this ability.",
        "runemarks": []
    },
    {
        "_id": "0f860443",
        "name": "Swift Climb",
        "warband": "Corvus Cabal",
        "cost": "double",
        "description": "Until the end of this fighter's activation, do not count the vertical distance moved when this fighter is climbing.",
        "runemarks": [
            "champion"
        ]
    },
    {
        "_id": "d9fa1342",
        "name": "Grisly Trophy",
        "warband": "Corvus Cabal",
        "cost": "triple",
        "description": "A fighter can only use this ability if an enemy fighter has been taken down by an attack action made by them this activation. Until the end of the battle round, add 1 to the Attacks characteristic of melee attack actions made by visible friendly fighters while they are within 9\" of this fighter.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "bfe8d30f",
        "name": "Swooping Attack",
        "warband": "Corvus Cabal",
        "cost": "triple",
        "description": "This fighter makes a bonus move action. In addition, if the fighter finishes that move action 2\" or more vertically lower than their starting position, they can make a bonus attack action.",
        "runemarks": [
            "agile"
        ]
    },
    {
        "_id": "c5a997f2",
        "name": "Death from Above",
        "warband": "Corvus Cabal",
        "cost": "quad",
        "description": "This fighter makes a bonus move action. Then, they can make a bonus attack action. Add 1 to the Strength characteristic of that attack action if the fighter finished the move action 2\" or more vertically lower than their starting position.",
        "runemarks": []
    },
    {
        "_id": "a4f11133",
        "name": "Wall Run",
        "warband": "Corvus Cabal",
        "cost": "double",
        "description": "A fighter can use this ability only if they are within 1\" of a dungeon wall.  Until the end of this fighter's next move action this activation, this fighter can move over other fighters as if they could fly.  However, during that move action, this fighter must stay within 1\" of a dungeon wall.",
        "runemarks": []
    },
    {
        "_id": "54d55383",
        "name": "Running Strike",
        "warband": "Corvus Cabal",
        "cost": "quad",
        "description": "This fighter uses the \"Wall Run\" ability, then makes a bonus move action, and can then make a bonus attack action.",
        "runemarks": []
    },
    {
        "_id": "76419c03",
        "name": "Raptor Strike",
        "warband": "Corvus Cabal",
        "cost": "reaction",
        "description": "A fighter can make this reaction after an enemy fighter finishes a move action visible to this fighter, within 5\" horizontally and vertically lower than this fighter. This fighter makes a bonus move action and must finish closer to that enemy fighter than they were at the start of that move action. If this fighter ends that move within 1\" of that enemy fighter, this fighter does not suffer impact damage and that enemy fighter suffers impact damage.",
        "runemarks": []
    },
    {
        "_id": "f90c6d85",
        "name": "Plunging Killers",
        "warband": "Corvus Cabal",
        "cost": "battletrait",
        "description": "Add 2 of the Strength characteristics of melee attack actions made by friendly fighters with this battle trait if they fell this activation.",
        "runemarks": []
    }
]

=== krisling049/warcry_data/data/Destruction/kruleboyz_abilities.json
[
    {
        "_id": "0af73084",
        "name": "Gang Up",
        "warband": "Da Kunnin' Krew",
        "cost": "double",
        "description": "Pick a visible friendly fighter within 6\" of this fighter that has both the Da Kunnin' Krew and the Minion runemarks and has not activated yet this battle round.  You can activate that fighter immediately after this fighter's activation ends.",
        "runemarks": [
            "minion"
        ]
    },
    {
        "_id": "f56775f9",
        "name": "Master of Murk",
        "warband": "Da Kunnin' Krew",
        "cost": "double",
        "description": "A fighter can only use this ability if they are within 1\" of an obstacle.  Until the end of the battle round, as long as this fighter is within 1\" of an obstacle, they cannot be picked as the target of attack actions made by enemy fighters that are more than 8\" away.",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "759bc2a8",
        "name": "Sneaky Snares",
        "warband": "Da Kunnin' Krew",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 2\" of this fighter and roll a dice.  On a roll of 2+, until the end of the battle round, that enemy fighter cannot make move actions or disengage actions.",
        "runemarks": [
            "scout"
        ]
    },
    {
        "_id": "c867eb77",
        "name": "Aimed Shot",
        "warband": "Kruleboyz",
        "cost": "double",
        "description": "A fighter can only use this ability if they have not made a move action this activation. If this fighter's next action is a missile attack action, critical hits are scored on a 4+ for that attack action.",
        "runemarks": [
            "trapper"
        ]
    },
    {
        "_id": "2525ab3f",
        "name": "Bone-crushing Bite",
        "warband": "Kruleboyz",
        "cost": "double",
        "description": "Pick a visible enemy fighter within 1\" of this fighter and roll a number of dice equal to half the value of this ability (rounding up). For each roll of 3+, allocate 3 damage points to that fighter.",
        "runemarks": [
            "hero",
            "mount"
        ]
    },
    {
        "_id": "26a4ea2f",
        "name": "Venom-encrusted Weapon",
        "warband": "Kruleboyz",
        "cost": "double",
        "description": "Until the end of this fighter's activation, add 1 to the damage points allocated to enemy fighters by each hit and critical hit from attack actions made by this fighter.",
        "runemarks": [
            "warrior"
        ]
    },
    {
        "_id": "1af77c38",
        "name": "You Hold 'Em Off",
        "warband": "Kruleboyz",
        "cost": "double",
        "description": "Pick a friendly fighter with both the Kruleboyz faction runemark and the Bulwark runemark within 3\" of this fighter. That fighter can make a bonus move action or a bonus attack action.",
        "runemarks": [
            "berserker",
            "hero"
        ]
    },
    {
        "_id": "f7eaecfa",
        "name": "Breath of the Mire-drake",
        "warband": "Kruleboyz",
        "cost": "triple",
        "description": "Roll a dice for each visible enemy fighter within 3\" of this fighter. On a roll of 3-4, allocate 1 damage point to the fighter being rolled for. On a roll of 5+, allocate a number of damage points to the fighter being rolled for equal to the value of this ability.",
        "runemarks": [
            "icon-bearer",
            "hero"
        ]
    },
    {
        "_id": "f2ad33bb",
        "name": "Brewed Elixir",
        "warband": "Kruleboyz",
        "cost": "triple",
        "description": "Pick a friendly fighter within 1\" of this fighter and roll a number of dice equal to the value of this ability. For each roll of 4+, remove up to 3 damage points allocated to that fighter.",
        "runemarks": [
            "destroyer"
        ]
    },
    {
        "_id": "c7f0da76",
        "name": "Stab 'Em Good",
        "warband": "Kruleboyz",
        "cost": "triple",
        "description": "Until the end of the battle round, add 1 to the Attacks characteristic of attack actions that have the Dagger runemark made by friendly fighters with the Minion runemark while they are within 6\" of this fighter.",
        "runemarks": [
            "champion"
        ]
    },
    {
        "_id": "8c31db62",
        "name": "Summon Boggy Mist",
        "warband": "Kruleboyz",
        "cost": "triple",
        "description": "Until the end of the battle round, subtract 1 from the Attacks characteristic (to a minimum of 1) of attack actions made by enemy fighters while they are within 6\" of this fighter.",
        "runemarks": [
            "mystic",
            "hero"
        ]
    },
    {
        "_id": "f8fa5631",
        "name": "Kunnin' Attack",
        "warband": "Kruleboyz",
        "cost": "quad",
        "description": "A fighter can use this ability only if there are more friendly fighters with the Warrior runemark within 6\" of this fighter than there are enemy fighters within 6\" of this fighter. Those friendly fighters can each make a bonus move action or a bonus melee attack action (some can make a bonus move action and others can make a bonus melee attack action).",
        "runemarks": [
            "hero"
        ]
    },
    {
        "_id": "64b1818c",
        "name": "Kunnin' Trap",
        "warband": "Kruleboyz",
        "cost": "reaction",
        "description": "A fighter can make this reaction after an enemy fighter finishes a move action visible to this fighter and within 3\" of this fighter. Pick another friendly fighter within 3\" of this fighter. That fighter makes a bonus attack action that must target the enemy fighter that made the move action.",
        "runemarks": []
    }
]

=== krisling049/warcry_data/data/Death/pyregheists_abilities.json
[
  {
    "_id": "22050b34",
    "name": "Balefire Cremation",
    "warband": "Pyregheists",
    "cost": "passive",
    "description": "When an ability tells you to cremate a fighter, remove that fighter from the battlefield and place a Pyre token at the centre of the space occupied by that fighter. At the end of the battle round, after determining control of objectives, allocate 3 damage to each enemy fighter within 1\" of the centre of one or more Pyre tokens.",
    "runemarks": []
  },

  {
    "_id": "78f7d995",
    "name": "Fan the Flames",
    "warband": "Pyregheists",
    "cost": "double",
    "description": "Add 1 to the damage points allocated by each hit and each critical hit form the next melee attack action made by this fighter this activation.",
    "runemarks": []
  },

  {
    "_id": "20a38f4f",
    "name": "Pyrerobber's Curse",
    "warband": "Pyregheists",
    "cost": "double",
    "description": "Until the end of this fighter's activation, add 1 to the Strength characteristic of attack actions made by this fighter. Until the end of this fighter's activation, when their attack action takes down an enemy fighter, cremate that enemy fighter.",
    "runemarks": ["frenzied"]
  },

  {
    "_id": "779e2be9",
    "name": "Unblinking Guardian",
    "warband": "Pyregheists",
    "cost": "double",
    "description": "Until the end of the battle round, add 1 to the Toughness characteristic of friendly fighters with the Elite or Hero runemarks while they are within 3\" of this fighter.",
    "runemarks": ["elite"]
  },

  {
    "_id": "85b75c37",
    "name": "Light the Pyre",
    "warband": "Pyregheists",
    "cost": "triple",
    "description": "A fighter can only use this ability when their attack action takes down an enemy fighter. Cremate that enemy fighter.",
    "runemarks": []
  },

  {
    "_id": "6bb4417d",
    "name": "Soulblaze",
    "warband": "Pyregheists",
    "cost": "triple",
    "description": "A fighter can only use this ability if an enemy fighter has been taken down this battle round. Pick a number of visible friendly fighters with the Pyregheists runemark equal to half the value of this ability (rounding up). Each fighter you picked can make a bonus move action or a bonus attack action (some can make a bonus move action and others can make a bonus attack action).",
    "runemarks": ["hero"]
  },

  {
    "_id": "ad5d0eb1",
    "name": "Agonising Penance",
    "warband": "Pyregheists",
    "cost": "quad",
    "description": "Pick a visible enemy fighter within 6\" of this fighter. That enemy fighter makes a bonus move action directly towards the closest other fighter from their warband, as if they were jumping, a number of inches equal to the value of this ability. When doing so, they can move away from enemy fighters within 1\" at the start of that move action. After that move action, allocate 3 damage points to that fighter and to each other enemy fighter within 2\" of that fighter. Cremate each fighter taken down by this ability.",
    "runemarks": []
  }
]
