=== krisling049/warcry_data/data/schemas/fighter_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/data/schemas/fighter_schema.json",
	"type": "object",
	"title": "Fighter Schema",
	"required": [
		"_id",
		"bladeborn",
		"grand_alliance",
		"movement",
		"name",
		"points",
		"runemarks",
		"toughness",
		"warband",
		"weapons",
		"wounds"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this fighter. In generated from the beginning of a uuid4.",
			"examples": [
				"c0fadcc5"
			]
		},
		"bladeborn": {
			"type": "string",
			"description": "If the fighter is Bladeborn, their bladeborn warband name. If not bladeborn then an empty string",
			"default": "",
			"examples": [
				"Hedrakka's Madmob"
			]
		},
		"grand_alliance": {
			"type": "string",
			"description": "Grand Alliance name, lowercase",
			"enum": [
				"chaos",
				"death",
				"destruction",
				"order"
			],
			"examples": [
				"destruction"
			]
		},
		"movement": {
			"type": "integer",
			"description": "Movement characteristic of the fighter",
			"examples": [
				4
			]
		},
		"name": {
			"type": "string",
			"description": "Name of the fighter as it appears on their profile card",
			"examples": [
				"Savage Orruk Arrowboy"
			]
		},
		"points": {
			"type": "integer",
			"description": "Points value of the fighter",
			"examples": [
				110
			]
		},
		"runemarks": {
			"type": "array",
			"default": [],
			"description": "Runemark names, lowercase. Do not include faction runemarks",
			"items": {
				"type": "string",
				"examples": [
					"destroyer"
				]
			}
		},
		"toughness": {
			"type": "integer",
			"description": "Toughness characteristic of the fighter",
			"examples": [
				3
			]
		},
		"warband": {
			"type": "string",
			"description": "Name of the fighter's faction, as defined by their faction runemark",
			"examples": [
				"Bonesplitterz"
			]
		},
		"weapons": {
			"type": "array",
			"description": "Each attack profile available to the fighter",
			"items": {
				"type": "object",
				"required": [
					"attacks",
					"dmg_crit",
					"dmg_hit",
					"max_range",
					"min_range",
					"runemark",
					"strength"
				],
				"properties": {
					"attacks": {
						"type": "integer",
						"examples": [
							3,
							2
						]
					},
					"dmg_crit": {
						"type": "integer",
						"examples": [
							2,
							3
						]
					},
					"dmg_hit": {
						"type": "integer",
						"examples": [
							1
						]
					},
					"max_range": {
						"type": "integer",
						"examples": [
							1,
							15
						]
					},
					"min_range": {
						"type": "integer",
						"description": "If no minimum range, use 0",
						"examples": [
							0,
							3
						]
					},
					"runemark": {
						"type": "string",
						"description": "Runemark of this weapon profile",
						"examples": [
							"unarmed",
							"ranged"
						]
					},
					"strength": {
						"type": "integer",
						"title": "The strength Schema",
						"examples": [
							3
						]
					}
				},
				"examples": [
					{
						"attacks": 3,
						"dmg_crit": 2,
						"dmg_hit": 1,
						"max_range": 1,
						"min_range": 0,
						"runemark": "unarmed",
						"strength": 3
					},
					{
						"attacks": 2,
						"dmg_crit": 3,
						"dmg_hit": 1,
						"max_range": 15,
						"min_range": 3,
						"runemark": "ranged",
						"strength": 3
					}
				]
			}
		},
		"wounds": {
			"type": "integer",
			"description": "Wounds characteristic of the fighter",
			"examples": [
				15
			]
		}
	},
	"examples": [
		{
			"_id": "c0fadcc5",
			"bladeborn": "",
			"grand_alliance": "destruction",
			"movement": 4,
			"name": "Savage Orruk Arrowboy",
			"points": 110,
			"runemarks": [
				"destroyer"
			],
			"toughness": 3,
			"warband": "Bonesplitterz",
			"weapons": [
				{
					"attacks": 3,
					"dmg_crit": 2,
					"dmg_hit": 1,
					"max_range": 1,
					"min_range": 0,
					"runemark": "unarmed",
					"strength": 3
				},
				{
					"attacks": 2,
					"dmg_crit": 3,
					"dmg_hit": 1,
					"max_range": 15,
					"min_range": 3,
					"runemark": "ranged",
					"strength": 3
				}
			],
			"wounds": 15
		}
	]
}

=== krisling049/warcry_data/data/Chaos/the_unmade.json
[
    {
        "_id": "ad8709a0",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "name": "Awakened One with Brutal Polearm",
        "points": 65,
        "runemarks": [],
        "toughness": 3,
        "warband": "The Unmade",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 3
            }
        ],
        "wounds": 10
    },
    {
        "_id": "b2e31ca2",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 3,
        "name": "Awakened One with Flail",
        "points": 65,
        "runemarks": [],
        "toughness": 4,
        "warband": "The Unmade",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            },
            {
                "attacks": 3,
                "dmg_crit": 2,
                "dmg_hit": 1,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 3
            }
        ],
        "wounds": 20
    },
    {
        "_id": "31740359",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "name": "Ascended One",
        "points": 110,
        "runemarks": [
            "warrior"
        ],
        "toughness": 4,
        "warband": "The Unmade",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "wounds": 10
    },
    {
        "_id": "ac71c483",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 5,
        "name": "Joyous One",
        "points": 140,
        "runemarks": [
            "destroyer"
        ],
        "toughness": 4,
        "warband": "The Unmade",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 4
            }
        ],
        "wounds": 15
    },
    {
        "_id": "9ecfd2ac",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 8,
        "name": "Blissful One",
        "points": 255,
        "runemarks": [
            "hero"
        ],
        "toughness": 4,
        "warband": "The Unmade",
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 6,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 4
            }
        ],
        "wounds": 20
    }
]

=== krisling049/warcry_data/data/Chaos/chaos_ally.json
[
    {
        "_id": "0014b0b1",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 5,
        "name": "Fomoroid Crusher",
        "points": 260,
        "runemarks": [
            "ally",
            "destroyer"
        ],
        "toughness": 6,
        "warband": "chaos_ally",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 1,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 6
            }
        ],
        "wounds": 35
    },
    {
        "_id": "10fcdb0b",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 8,
        "name": "Mindstealer Sphiranx",
        "points": 260,
        "runemarks": [
            "ally",
            "mystic"
        ],
        "toughness": 5,
        "warband": "chaos_ally",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 5
            }
        ],
        "wounds": 30
    },
    {
        "_id": "f2e9c403",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 5,
        "name": "Ogroid Myrmidon",
        "points": 265,
        "runemarks": [
            "ally",
            "champion"
        ],
        "toughness": 6,
        "warband": "chaos_ally",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 5
            }
        ],
        "wounds": 30
    },
    {
        "_id": "2137fdcf",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 10,
        "name": "Centaurian Marshal",
        "points": 295,
        "runemarks": [
            "ally",
            "bulwark",
            "mount"
        ],
        "toughness": 5,
        "warband": "chaos_ally",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 6,
                "dmg_hit": 3,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 5
            },
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 3,
                "min_range": 0,
                "runemark": "spear",
                "strength": 6
            }
        ],
        "wounds": 35
    }
]

=== krisling049/warcry_data/data/Destruction/destruction_monster.json
[
    {
        "_id": "b616e449",
        "bladeborn": "",
        "grand_alliance": "destruction",
        "movement": 5,
        "name": "Dankhold Troggoth",
        "points": 375,
        "runemarks": [
            "monster"
        ],
        "toughness": 4,
        "warband": "destruction_monster",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 1,
                "min_range": 2,
                "runemark": "club",
                "strength": 5
            }
        ],
        "wounds": 45
    },
    {
        "_id": "2c7b4722",
        "bladeborn": "",
        "grand_alliance": "destruction",
        "movement": 6,
        "name": "Aleguzzler Gargant",
        "points": 420,
        "runemarks": [
            "monster",
            "brute"
        ],
        "toughness": 4,
        "warband": "destruction_monster",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 1,
                "min_range": 2,
                "runemark": "club",
                "strength": 5
            }
        ],
        "wounds": 45
    },
    {
        "_id": "483abb24",
        "bladeborn": "",
        "grand_alliance": "destruction",
        "movement": 8,
        "name": "Skitterstrand Arachnarok",
        "points": 475,
        "runemarks": [
            "monster",
            "destroyer"
        ],
        "toughness": 4,
        "warband": "destruction_monster",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 1,
                "min_range": 1,
                "runemark": "fangs",
                "strength": 5
            }
        ],
        "wounds": 55
    }
]

=== krisling049/warcry_data/data/Order/blacktalons_fighters.json
[
    {
        "_id": "fe3c9b45",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Hendrick, The Silver Wolf",
        "points": 155,
        "runemarks": [
            "champion"
        ],
        "toughness": 5,
        "warband": "Blacktalons",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            },
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 5
            }
        ],
        "wounds": 25
    },
    {
        "_id": "5feaf59c",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 5,
        "name": "Lorai, Child of the Abyss",
        "points": 160,
        "runemarks": [
            "fly",
            "mystic"
        ],
        "toughness": 3,
        "warband": "Blacktalons",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            },
            {
                "attacks": 3,
                "dmg_crit": 7,
                "dmg_hit": 3,
                "max_range": 7,
                "min_range": 3,
                "runemark": "blast",
                "strength": 3
            }
        ],
        "wounds": 20
    },
    {
        "_id": "349b6dfe",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Shakana Goldenblade",
        "points": 180,
        "runemarks": [
            "destroyer"
        ],
        "toughness": 5,
        "warband": "Blacktalons",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            },
            {
                "attacks": 4,
                "dmg_crit": 2,
                "dmg_hit": 1,
                "max_range": 15,
                "min_range": 3,
                "runemark": "ranged",
                "strength": 3
            }
        ],
        "wounds": 25
    },
    {
        "_id": "a0fb0704",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Rostus Oxenhammer",
        "points": 200,
        "runemarks": [
            "champion"
        ],
        "toughness": 6,
        "warband": "Blacktalons",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 6,
                "dmg_hit": 3,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 6
            }
        ],
        "wounds": 25
    },
    {
        "_id": "41cc2020",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 7,
        "name": "Neave Blacktalon",
        "points": 285,
        "runemarks": [
            "hero"
        ],
        "toughness": 5,
        "warband": "Blacktalons",
        "weapons": [
            {
                "attacks": 6,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            },
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 10,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "wounds": 30
    }
]

=== krisling049/warcry_data/data/Order/stormcast_eternals_ruination_chamber_fighters.json
[
	{
		"_id": "5771e4f5",
		"bladeborn": "",
		"grand_alliance": "order",
		"movement": 10,
		"name": "Prosecutor-Prime",
		"points": 205,
		"runemarks": [
			"hero",
			"champion",
			"fly"
		],
		"toughness": 4,
		"warband": "Stormcast Eternals Ruination Chamber",
		"weapons": [
			{
				"attacks": 4,
				"dmg_crit": 4,
				"dmg_hit": 2,
				"max_range": 1,
				"min_range": 0,
				"runemark": "spear",
				"strength": 4
			},
			{
				"attacks": 2,
				"dmg_crit": 4,
				"dmg_hit": 2,
				"max_range": 12,
				"min_range": 3,
				"runemark": "ranged",
				"strength": 4
			}
		],
		"wounds": 20
	},
	{
		"_id": "dc3af7bb",
		"bladeborn": "",
		"grand_alliance": "order",
		"movement": 10,
		"name": "Prosecutor",
		"points": 180,
		"runemarks": [
			"fly",
			"champion"
		],
		"toughness": 4,
		"warband": "Stormcast Eternals Ruination Chamber",
		"weapons": [
			{
				"attacks": 3,
				"dmg_crit": 4,
				"dmg_hit": 2,
				"max_range": 1,
				"min_range": 0,
				"runemark": "axe",
				"strength": 4
			},
			{
				"attacks": 2,
				"dmg_crit": 4,
				"dmg_hit": 2,
				"max_range": 12,
				"min_range": 3,
				"runemark": "spear",
				"strength": 4
			}
		],
		"wounds": 15
	},
	{
		"_id": "149e002e",
		"bladeborn": "",
		"grand_alliance": "order",
		"movement": 4,
		"name": "Reclusian-Prime",
		"points": 195,
		"runemarks": [
			"hero",
			"terrifying"
		],
		"toughness": 6,
		"warband": "Stormcast Eternals Ruination Chamber",
		"weapons": [
			{
				"attacks": 4,
				"dmg_crit": 5,
				"dmg_hit": 3,
				"max_range": 1,
				"min_range": 0,
				"runemark": "axe",
				"strength": 5
			}
		],
		"wounds": 25
	},
	{
		"_id": "614719d2",
		"bladeborn": "",
		"grand_alliance": "order",
		"movement": 4,
		"name": "Reclusian",
		"points": 160,
		"runemarks": [
			"terrifying"
		],
		"toughness": 6,
		"warband": "Stormcast Eternals Ruination Chamber",
		"weapons": [
			{
				"attacks": 4,
				"dmg_crit": 5,
				"dmg_hit": 3,
				"max_range": 1,
				"min_range": 0,
				"runemark": "axe",
				"strength": 4
			}
		],
		"wounds": 20
	},
	{
		"_id": "09eadea6",
		"bladeborn": "",
		"grand_alliance": "order",
		"movement": 4,
		"name": "Lord-Veritant",
		"points": 190,
		"runemarks": [
			"hero",
			"mystic"
		],
		"toughness": 5,
		"warband": "Stormcast Eternals Ruination Chamber",
		"weapons": [
			{
				"attacks": 3,
				"dmg_crit": 4,
				"dmg_hit": 2,
				"max_range": 1,
				"min_range": 0,
				"runemark": "sword",
				"strength": 4
			},
			{
				"attacks": 2,
				"dmg_crit": 7,
				"dmg_hit": 3,
				"max_range": 7,
				"min_range": 3,
				"runemark": "blast",
				"strength": 4
			}
		],
		"wounds": 20
	},
	{
		"_id": "7ace3e66",
		"bladeborn": "",
		"grand_alliance": "order",
		"movement": 6,
		"name": "Gryph-Crow",
		"points": 60,
		"runemarks": [
			"beast"
		],
		"toughness": 3,
		"warband": "Stormcast Eternals Ruination Chamber",
		"weapons": [
			{
				"attacks": 3,
				"dmg_crit": 3,
				"dmg_hit": 1,
				"max_range": 1,
				"min_range": 0,
				"runemark": "claws",
				"strength": 3
			}
		],
		"wounds": 6
	},
	{
		"_id": "557afa14",
		"bladeborn": "",
		"grand_alliance": "order",
		"movement": 10,
		"name": "Knight-Azyros",
		"points": 255,
		"runemarks": [
			"hero",
			"icon-bearer",
			"fly"
		],
		"toughness": 5,
		"warband": "Stormcast Eternals Ruination Chamber",
		"weapons": [
			{
				"attacks": 4,
				"dmg_crit": 4,
				"dmg_hit": 2,
				"max_range": 1,
				"min_range": 0,
				"runemark": "sword",
				"strength": 4
			}
		],
		"wounds": 28
	},
	{
		"_id": "2dfe9f6e",
		"bladeborn": "",
		"grand_alliance": "order",
		"movement": 10,
		"name": "Lord-Vigilant on Gryph-Stalker",
		"points": 280,
		"runemarks": [
			"hero",
			"mount"
		],
		"toughness": 5,
		"warband": "Stormcast Eternals Ruination Chamber",
		"weapons": [
			{
				"attacks": 3,
				"dmg_crit": 6,
				"dmg_hit": 3,
				"max_range": 1,
				"min_range": 0,
				"runemark": "sword",
				"strength": 4
			}
		],
		"wounds": 38
	},
	{
		"_id": "9683def2",
		"bladeborn": "",
		"grand_alliance": "order",
		"movement": 4,
		"name": "Lord-Terminos",
		"points": 225,
		"runemarks": [
			"hero",
			"destroyer"
		],
		"toughness": 5,
		"warband": "Stormcast Eternals Ruination Chamber",
		"weapons": [
			{
				"attacks": 4,
				"dmg_crit": 6,
				"dmg_hit": 3,
				"max_range": 1,
				"min_range": 0,
				"runemark": "axe",
				"strength": 5
			}
		],
		"wounds": 28
	}
]
