=== krisling049/warcry_data/data/schemas/fighter_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/data/schemas/fighter_schema.json",
	"type": "object",
	"title": "Fighter Schema",
	"required": [
		"_id",
		"bladeborn",
		"grand_alliance",
		"movement",
		"name",
		"points",
		"runemarks",
		"toughness",
		"warband",
		"weapons",
		"wounds"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this fighter. In generated from the beginning of a uuid4.",
			"examples": [
				"c0fadcc5"
			]
		},
		"bladeborn": {
			"type": "string",
			"description": "If the fighter is Bladeborn, their bladeborn warband name. If not bladeborn then an empty string",
			"default": "",
			"examples": [
				"Hedrakka's Madmob"
			]
		},
		"grand_alliance": {
			"type": "string",
			"description": "Grand Alliance name, lowercase",
			"enum": [
				"chaos",
				"death",
				"destruction",
				"order"
			],
			"examples": [
				"destruction"
			]
		},
		"movement": {
			"type": "integer",
			"description": "Movement characteristic of the fighter",
			"examples": [
				4
			]
		},
		"name": {
			"type": "string",
			"description": "Name of the fighter as it appears on their profile card",
			"examples": [
				"Savage Orruk Arrowboy"
			]
		},
		"points": {
			"type": "integer",
			"description": "Points value of the fighter",
			"examples": [
				110
			]
		},
		"runemarks": {
			"type": "array",
			"default": [],
			"description": "Runemark names, lowercase. Do not include faction runemarks",
			"items": {
				"type": "string",
				"examples": [
					"destroyer"
				]
			}
		},
		"toughness": {
			"type": "integer",
			"description": "Toughness characteristic of the fighter",
			"examples": [
				3
			]
		},
		"warband": {
			"type": "string",
			"description": "Name of the fighter's faction, as defined by their faction runemark",
			"examples": [
				"Bonesplitterz"
			]
		},
		"weapons": {
			"type": "array",
			"description": "Each attack profile available to the fighter",
			"items": {
				"type": "object",
				"required": [
					"attacks",
					"dmg_crit",
					"dmg_hit",
					"max_range",
					"min_range",
					"runemark",
					"strength"
				],
				"properties": {
					"attacks": {
						"type": "integer",
						"examples": [
							3,
							2
						]
					},
					"dmg_crit": {
						"type": "integer",
						"examples": [
							2,
							3
						]
					},
					"dmg_hit": {
						"type": "integer",
						"examples": [
							1
						]
					},
					"max_range": {
						"type": "integer",
						"examples": [
							1,
							15
						]
					},
					"min_range": {
						"type": "integer",
						"description": "If no minimum range, use 0",
						"examples": [
							0,
							3
						]
					},
					"runemark": {
						"type": "string",
						"description": "Runemark of this weapon profile",
						"examples": [
							"unarmed",
							"ranged"
						]
					},
					"strength": {
						"type": "integer",
						"title": "The strength Schema",
						"examples": [
							3
						]
					}
				},
				"examples": [
					{
						"attacks": 3,
						"dmg_crit": 2,
						"dmg_hit": 1,
						"max_range": 1,
						"min_range": 0,
						"runemark": "unarmed",
						"strength": 3
					},
					{
						"attacks": 2,
						"dmg_crit": 3,
						"dmg_hit": 1,
						"max_range": 15,
						"min_range": 3,
						"runemark": "ranged",
						"strength": 3
					}
				]
			}
		},
		"wounds": {
			"type": "integer",
			"description": "Wounds characteristic of the fighter",
			"examples": [
				15
			]
		}
	},
	"examples": [
		{
			"_id": "c0fadcc5",
			"bladeborn": "",
			"grand_alliance": "destruction",
			"movement": 4,
			"name": "Savage Orruk Arrowboy",
			"points": 110,
			"runemarks": [
				"destroyer"
			],
			"toughness": 3,
			"warband": "Bonesplitterz",
			"weapons": [
				{
					"attacks": 3,
					"dmg_crit": 2,
					"dmg_hit": 1,
					"max_range": 1,
					"min_range": 0,
					"runemark": "unarmed",
					"strength": 3
				},
				{
					"attacks": 2,
					"dmg_crit": 3,
					"dmg_hit": 1,
					"max_range": 15,
					"min_range": 3,
					"runemark": "ranged",
					"strength": 3
				}
			],
			"wounds": 15
		}
	]
}

=== krisling049/warcry_data/data/Order/order_of_azyr_fighters.json
[
    {
        "_id": "1d0c5423",
        "bladeborn": "Hexbane's Hunters",
        "grand_alliance": "order",
        "movement": 6,
        "name": "Grotbiter",
        "points": 55,
        "runemarks": [
            "beast"
        ],
        "toughness": 3,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 3
            }
        ],
        "wounds": 6
    },
    {
        "_id": "84a2c1df",
        "bladeborn": "Hexbane's Hunters",
        "grand_alliance": "order",
        "movement": 6,
        "name": "Ratspike",
        "points": 55,
        "runemarks": [
            "beast"
        ],
        "toughness": 3,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 3
            }
        ],
        "wounds": 6
    },
    {
        "_id": "93db72a2",
        "bladeborn": "Hexbane's Hunters",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Brydget Axwold",
        "points": 95,
        "runemarks": [
            "warrior"
        ],
        "toughness": 3,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 3
            },
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 6,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 5
            }
        ],
        "wounds": 10
    },
    {
        "_id": "23ee45b1",
        "bladeborn": "Hexbane's Hunters",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Aemos Duncarrow",
        "points": 105,
        "runemarks": [
            "warrior"
        ],
        "toughness": 4,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            }
        ],
        "wounds": 15
    },
    {
        "_id": "210e343f",
        "bladeborn": "Hexbane's Hunters",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Haskel Hexbane",
        "points": 125,
        "runemarks": [
            "hero",
            "warrior"
        ],
        "toughness": 4,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 3
            },
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "wounds": 20
    },
    {
        "_id": "5a274449",
        "bladeborn": "Hexbane's Hunters",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Quiet Pock",
        "points": 150,
        "runemarks": [
            "brute",
            "warrior"
        ],
        "toughness": 4,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 3
            },
            {
                "attacks": 2,
                "dmg_crit": 6,
                "dmg_hit": 3,
                "max_range": 15,
                "min_range": 3,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "wounds": 10
    },
    {
        "_id": "e3fdafae",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Hanniver Toll",
        "points": 125,
        "runemarks": [
            "hero",
            "agile",
            "warrior"
        ],
        "toughness": 3,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 3
            },
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "wounds": 20
    },
    {
        "_id": "b77deaf5",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Armand Callis",
        "points": 130,
        "runemarks": [
            "scout",
            "warrior"
        ],
        "toughness": 4,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            },
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "wounds": 18
    },
    {
        "_id": "621649f9",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Valius, The Keeper Aqshian",
        "points": 220,
        "runemarks": [
            "bulwark",
            "warrior"
        ],
        "toughness": 6,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 3,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 5
            }
        ],
        "wounds": 30
    },
    {
        "_id": "2a55d1ea",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Mistress Verentia",
        "points": 100,
        "runemarks": [
            "terrifying"
        ],
        "toughness": 3,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 3
            },
            {
                "attacks": 1,
                "dmg_crit": 6,
                "dmg_hit": 3,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "wounds": 15
    },
    {
        "_id": "636f0302",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Lyssa Revenya",
        "points": 75,
        "runemarks": [
            "trapper",
            "fly"
        ],
        "toughness": 3,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 3
            }
        ],
        "wounds": 15
    },
    {
        "_id": "36e88245",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 6,
        "name": "Balthus",
        "points": 95,
        "runemarks": [
            "beast"
        ],
        "toughness": 4,
        "warband": "Order of Azyr",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 4
            }
        ],
        "wounds": 8
    }
]

=== krisling049/warcry_data/data/Death/pyregheists_fighters.json
[
    {
        "_id": "8a46a02f",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 4,
        "name": "Deacon of Flames with Brazier Staff",
        "points": 190,
        "runemarks": [
            "hero",
            "fly"
        ],
        "toughness": 5,
        "warband": "Pyregheists",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "club",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 8,
                "min_range": 0,
                "runemark": "blast",
                "strength": 4
            }
        ],
        "wounds": 20
    },
    {
    "_id": "88993788",
    "bladeborn": "",
    "grand_alliance": "death",
    "movement": 4,
    "name": "Deacon of Flames with Pyrekeeper's Tongs",
    "points": 190,
    "runemarks": [
        "hero",
        "fly"
    ],
    "toughness": 5,
    "warband": "Pyregheists",
    "weapons": [
        {
            "attacks": 3,
            "dmg_crit": 4,
            "dmg_hit": 3,
            "max_range": 2,
            "min_range": 0,
            "runemark": "fangs",
            "strength": 5
        },
        {
            "attacks": 2,
            "dmg_crit": 4,
            "dmg_hit": 2,
            "max_range": 8,
            "min_range": 0,
            "runemark": "blast",
            "strength": 4
        }
    ],
    "wounds": 20
    },
    {
        "_id": "56aafd11",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 4,
        "name": "Balefire Guard with Scorch Flail",
        "points": 130,
        "runemarks": [
            "elite",
            "fly"
        ],
        "toughness": 5,
        "warband": "Pyregheists",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            }
        ],
        "wounds": 12
    },
    {
        "_id": "7387b93f",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 4,
        "name": "Balefire Guard with Flaming Halberd",
        "points": 130,
        "runemarks": [
            "elite",
            "fly"
        ],
        "toughness": 5,
        "warband": "Pyregheists",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            }
        ],
        "wounds": 12
    },
    {
        "_id": "5d752034",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 6,
        "name": "Torchwraith",
        "points": 115,
        "runemarks": [
            "frenzied",
            "fly"
        ],
        "toughness": 4,
        "warband": "Pyregheists",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "blast",
                "strength": 3
            },
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            }
        ],
        "wounds": 10
    },
    {
        "_id": "0a96e891",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 4,
        "name": "Flamewraith with Brazier-staff",
        "points": 100,
        "runemarks": [
            "fly"
        ],
        "toughness": 4,
        "warband": "Pyregheists",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "mace",
                "strength": 4
            }
        ],
        "wounds": 12
    },
    {
        "_id": "e87ff89f",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 4,
        "name": "Flamewraith with Balefire Torches",
        "points": 100,
        "runemarks": [
            "fly"
        ],
        "toughness": 4,
        "warband": "Pyregheists",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 4
            }
        ],
        "wounds": 12
    }
    
]

=== krisling049/warcry_data/data/Destruction/destruction_fighters.json
[
    {
        "_id": "b7da3ff4",
        "bladeborn": "",
        "grand_alliance": "destruction",
        "movement": 4,
        "name": "Fellwater Troggoth",
        "points": 175,
        "runemarks": [
            "thrall",
            "trapper",
            "bulwark"
        ],
        "toughness": 4,
        "warband": "destruction",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 5
            }
        ],
        "wounds": 28
    },
    {
        "_id": "a47621f5",
        "bladeborn": "",
        "grand_alliance": "destruction",
        "movement": 4,
        "name": "Rockgut Troggoth",
        "points": 185,
        "runemarks": [
            "thrall",
            "bulwark"
        ],
        "toughness": 5,
        "warband": "destruction",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 6,
                "dmg_hit": 3,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 5
            }
        ],
        "wounds": 28
    },
    {
        "_id": "b616e449",
        "bladeborn": "",
        "grand_alliance": "destruction",
        "movement": 5,
        "name": "Dankhold Troggoth",
        "points": 375,
        "runemarks": [
            "monster",
            "ferocious"
        ],
        "toughness": 4,
        "warband": "destruction",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 2,
                "min_range": 0,
                "runemark": "club",
                "strength": 5
            }
        ],
        "wounds": 45
    },
    {
        "_id": "2c7b4722",
        "bladeborn": "",
        "grand_alliance": "destruction",
        "movement": 6,
        "name": "Aleguzzler Gargant",
        "points": 420,
        "runemarks": [
            "monster",
            "brute"
        ],
        "toughness": 4,
        "warband": "destruction",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 2,
                "min_range": 0,
                "runemark": "club",
                "strength": 5
            }
        ],
        "wounds": 45
    },
    {
        "_id": "483abb24",
        "bladeborn": "",
        "grand_alliance": "destruction",
        "movement": 8,
        "name": "Skitterstrand Arachnarok",
        "points": 475,
        "runemarks": [
            "monster",
            "destroyer"
        ],
        "toughness": 4,
        "warband": "destruction",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 1,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 5
            }
        ],
        "wounds": 55
    }
]

=== krisling049/warcry_data/data/Order/order.json
[
    {
        "_id": "15bedde9",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 6,
        "name": "War Hydra",
        "points": 420,
        "runemarks": [
            "monster",
            "destroyer"
        ],
        "toughness": 4,
        "warband": "order",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 2,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 5
            }
        ],
        "wounds": 45
    },
    {
        "_id": "69f4a22a",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 6,
        "name": "Kharibdyss",
        "points": 425,
        "runemarks": [
            "monster",
            "berserker"
        ],
        "toughness": 4,
        "warband": "order",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 2,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 5
            }
        ],
        "wounds": 45
    }
]

=== krisling049/warcry_data/data/Death/askurgan_trueblades_fighters.json
[
    {
        "_id": "b8ec3ff9",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 5,
        "name": "Askurgan Acolyte with Bonehilt Falchion",
        "points": 90,
        "runemarks": [
            "elite"
        ],
        "toughness": 3,
        "warband": "Askurgan Trueblades",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 5
            }
        ],
        "wounds": 12
    },
    {
        "_id": "346f1247",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 5,
        "name": "Askurgan Acolyte with Throat-Taker",
        "points": 90,
        "runemarks": [
            "elite"
        ],
        "toughness": 3,
        "warband": "Askurgan Trueblades",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            }
        ],
        "wounds": 12
    },
    {
        "_id": "0bfbf81b",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 5,
        "name": "Askurgan Pariah",
        "points": 105,
        "runemarks": [
            "scout"
        ],
        "toughness": 3,
        "warband": "Askurgan Trueblades",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 5
            }
        ],
        "wounds": 18
    },
    {
        "_id": "c84a0f70",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 5,
        "name": "Askurgan Ascetic with Charnel Mace",
        "points": 115,
        "runemarks": [
            "elite",
            "destroyer"
        ],
        "toughness": 4,
        "warband": "Askurgan Trueblades",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 4,
                "dmg_hit": 3,
                "max_range": 1,
                "min_range": 0,
                "runemark": "mace",
                "strength": 6
            }
        ],
        "wounds": 15
    },
    {
        "_id": "009f3c74",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 5,
        "name": "Askurgan Ascetic with Howling Glaive",
        "points": 115,
        "runemarks": [
            "elite",
            "destroyer"
        ],
        "toughness": 4,
        "warband": "Askurgan Trueblades",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 5
            }
        ],
        "wounds": 15
    },
    {
        "_id": "ca3aa681",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 6,
        "name": "Curseblood",
        "points": 190,
        "runemarks": [
            "beast"
        ],
        "toughness": 4,
        "warband": "Askurgan Trueblades",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 5
            }
        ],
        "wounds": 25
    },
    {
        "_id": "fec8cb0a",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 5,
        "name": "Askurgan Exemplar",
        "points": 205,
        "runemarks": [
            "hero",
            "elite",
            "destroyer"
        ],
        "toughness": 4,
        "warband": "Askurgan Trueblades",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 6,
                "dmg_hit": 4,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 6
            }
        ],
        "wounds": 20
    }
]

=== krisling049/warcry_data/data/Death/death_monster.json
[
    {
        "_id": "cc01fb56",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 12,
        "name": "Terrorgheist",
        "points": 500,
        "runemarks": [
            "fly",
            "monster",
            "terrifying"
        ],
        "toughness": 4,
        "warband": "death_monster",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 2,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 5
            }
        ],
        "wounds": 50
    },
    {
        "_id": "033e033b",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 12,
        "name": "Zombie Dragon",
        "points": 540,
        "runemarks": [
            "fly",
            "monster",
            "brute"
        ],
        "toughness": 4,
        "warband": "death_monster",
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 2,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 5
            }
        ],
        "wounds": 50
    }
]
