=== krisling049/warcry_data/data/schemas/fighter_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/data/schemas/fighter_schema.json",
	"type": "object",
	"title": "Fighter Schema",
	"required": [
		"_id",
		"bladeborn",
		"grand_alliance",
		"movement",
		"name",
		"points",
		"runemarks",
		"toughness",
		"warband",
		"weapons",
		"wounds"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this fighter. In generated from the beginning of a uuid4.",
			"examples": [
				"c0fadcc5"
			]
		},
		"bladeborn": {
			"type": "string",
			"description": "If the fighter is Bladeborn, their bladeborn warband name. If not bladeborn then an empty string",
			"default": "",
			"examples": [
				"Hedrakka's Madmob"
			]
		},
		"grand_alliance": {
			"type": "string",
			"description": "Grand Alliance name, lowercase",
			"enum": [
				"chaos",
				"death",
				"destruction",
				"order"
			],
			"examples": [
				"destruction"
			]
		},
		"movement": {
			"type": "integer",
			"description": "Movement characteristic of the fighter",
			"examples": [
				4
			]
		},
		"name": {
			"type": "string",
			"description": "Name of the fighter as it appears on their profile card",
			"examples": [
				"Savage Orruk Arrowboy"
			]
		},
		"points": {
			"type": "integer",
			"description": "Points value of the fighter",
			"examples": [
				110
			]
		},
		"runemarks": {
			"type": "array",
			"default": [],
			"description": "Runemark names, lowercase. Do not include faction runemarks",
			"items": {
				"type": "string",
				"examples": [
					"destroyer"
				]
			}
		},
		"toughness": {
			"type": "integer",
			"description": "Toughness characteristic of the fighter",
			"examples": [
				3
			]
		},
		"warband": {
			"type": "string",
			"description": "Name of the fighter's faction, as defined by their faction runemark",
			"examples": [
				"Bonesplitterz"
			]
		},
		"weapons": {
			"type": "array",
			"description": "Each attack profile available to the fighter",
			"items": {
				"type": "object",
				"required": [
					"attacks",
					"dmg_crit",
					"dmg_hit",
					"max_range",
					"min_range",
					"runemark",
					"strength"
				],
				"properties": {
					"attacks": {
						"type": "integer",
						"examples": [
							3,
							2
						]
					},
					"dmg_crit": {
						"type": "integer",
						"examples": [
							2,
							3
						]
					},
					"dmg_hit": {
						"type": "integer",
						"examples": [
							1
						]
					},
					"max_range": {
						"type": "integer",
						"examples": [
							1,
							15
						]
					},
					"min_range": {
						"type": "integer",
						"description": "If no minimum range, use 0",
						"examples": [
							0,
							3
						]
					},
					"runemark": {
						"type": "string",
						"description": "Runemark of this weapon profile",
						"examples": [
							"unarmed",
							"ranged"
						]
					},
					"strength": {
						"type": "integer",
						"title": "The strength Schema",
						"examples": [
							3
						]
					}
				},
				"examples": [
					{
						"attacks": 3,
						"dmg_crit": 2,
						"dmg_hit": 1,
						"max_range": 1,
						"min_range": 0,
						"runemark": "unarmed",
						"strength": 3
					},
					{
						"attacks": 2,
						"dmg_crit": 3,
						"dmg_hit": 1,
						"max_range": 15,
						"min_range": 3,
						"runemark": "ranged",
						"strength": 3
					}
				]
			}
		},
		"wounds": {
			"type": "integer",
			"description": "Wounds characteristic of the fighter",
			"examples": [
				15
			]
		}
	},
	"examples": [
		{
			"_id": "c0fadcc5",
			"bladeborn": "",
			"grand_alliance": "destruction",
			"movement": 4,
			"name": "Savage Orruk Arrowboy",
			"points": 110,
			"runemarks": [
				"destroyer"
			],
			"toughness": 3,
			"warband": "Bonesplitterz",
			"weapons": [
				{
					"attacks": 3,
					"dmg_crit": 2,
					"dmg_hit": 1,
					"max_range": 1,
					"min_range": 0,
					"runemark": "unarmed",
					"strength": 3
				},
				{
					"attacks": 2,
					"dmg_crit": 3,
					"dmg_hit": 1,
					"max_range": 15,
					"min_range": 3,
					"runemark": "ranged",
					"strength": 3
				}
			],
			"wounds": 15
		}
	]
}

=== krisling049/warcry_data/data/Chaos/horns_of_hashut.json
[
    {
        "_id": "18631d5e",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "name": "Shatterer",
        "points": 55,
        "runemarks": [],
        "toughness": 3,
        "warband": "Horns of Hashut",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 3
            }
        ],
        "wounds": 10
    },
    {
        "_id": "c723653b",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "name": "Demolisher with Crushing Weapon & Shield",
        "points": 105,
        "runemarks": [
            "warrior"
        ],
        "toughness": 5,
        "warband": "Horns of Hashut",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 3
            }
        ],
        "wounds": 12
    },
    {
        "_id": "270f5b6c",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "name": "Demolisher with Crushing Weapons",
        "points": 105,
        "runemarks": [
            "warrior"
        ],
        "toughness": 4,
        "warband": "Horns of Hashut",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 3
            }
        ],
        "wounds": 12
    },
    {
        "_id": "43f8944f",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "name": "Demolisher with Flamehurler",
        "points": 125,
        "runemarks": [
            "frenzied",
            "warrior"
        ],
        "toughness": 4,
        "warband": "Horns of Hashut",
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 3
            },
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 1,
                "max_range": 6,
                "min_range": 0,
                "runemark": "blast",
                "strength": 5
            }
        ],
        "wounds": 12
    },
    {
        "_id": "3334417c",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "name": "Ruinator",
        "points": 125,
        "runemarks": [
            "brute",
            "warrior"
        ],
        "toughness": 4,
        "warband": "Horns of Hashut",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "bident",
                "strength": 4
            }
        ],
        "wounds": 15
    },
    {
        "_id": "a8ec49c8",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "name": "Ruinator Alpha with Heavy Flail",
        "points": 165,
        "runemarks": [
            "brute",
            "hero",
            "warrior"
        ],
        "toughness": 4,
        "warband": "Horns of Hashut",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "club",
                "strength": 4
            }
        ],
        "wounds": 20
    },
    {
        "_id": "6e00cdd3",
        "bladeborn": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "name": "Ruinator Alpha with War Bident",
        "points": 165,
        "runemarks": [
            "brute",
            "hero",
            "warrior"
        ],
        "toughness": 4,
        "warband": "Horns of Hashut",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "bident",
                "strength": 4
            }
        ],
        "wounds": 20
    }
]

=== krisling049/warcry_data/data/Order/stormcast_eternals_questor_soulsworn_fighters.json
[
    {
        "_id": "6e1b7w9z",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Errant-Questor Duelist with Twinblades",
        "points": 160,
        "runemarks": [
            "hero",
            "champion"
        ],
        "toughness": 5,
        "warband": "Stormcast Eternals Questor Soulsworn",
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "wounds": 20
    },
    {
        "_id": "u4nyw6a2",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Errant-Questor with Grandblade",
        "points": 165,
        "runemarks": [
            "hero",
            "destroyer"
        ],
        "toughness": 5,
        "warband": "Stormcast Eternals Questor Soulsworn",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 5
            }
        ],
        "wounds": 20
    },
    {
        "_id": "s5v8g2y4",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Errant-Questor with Grandaxe",
        "points": 165,
        "runemarks": [
            "hero",
            "destroyer"
        ],
        "toughness": 5,
        "warband": "Stormcast Eternals Questor Soulsworn",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            }
        ],
        "wounds": 20
    },
    {
        "_id": "y9p4k7d1",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Errant-Questor with Grandhammer",
        "points": 165,
        "runemarks": [
            "hero",
            "destroyer"
        ],
        "toughness": 5,
        "warband": "Stormcast Eternals Questor Soulsworn",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 3,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 6
            }
        ],
        "wounds": 20
    },
    {
        "_id": "j3h6t5r7",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Soulsworn Knight-Relictor",
        "points": 165,
        "runemarks": [
            "hero",
            "priest"
        ],
        "toughness": 5,
        "warband": "Stormcast Eternals Questor Soulsworn",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 3,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 5,
                "dmg_hit": 3,
                "max_range": 8,
                "min_range": 0,
                "runemark": "blast",
                "strength": 4
            }
        ],
        "wounds": 20
    },
    {
        "_id": "a7r5x8t9",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Questor-Prime",
        "points": 170,
        "runemarks": [
            "hero",
            "warrior"
        ],
        "toughness": 5,
        "warband": "Stormcast Eternals Questor Soulsworn",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "axe",
                "strength": 4
            }
        ],
        "wounds": 20
    },
    {
        "_id": "k9f3n1l6",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 4,
        "name": "Errant-Questor with Grandspear",
        "points": 170,
        "runemarks": [
            "hero"
        ],
        "toughness": 5,
        "warband": "Stormcast Eternals Questor Soulsworn",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 3,
                "min_range": 0,
                "runemark": "spear",
                "strength": 5
            }
        ],
        "wounds": 20
    }
]

=== krisling049/warcry_data/data/Order/ydrilan_riverblades_fighters.json
[
  {
    "_id": "ad524c22",
    "bladeborn": "",
    "grand_alliance": "order",
    "movement": 5,
    "name": "Pureflood Seneschal with Ydrilan Warglaive",
    "points": 205,
    "runemarks": ["elite", "hero"],
    "toughness": 4,
    "warband": "Ydrilan Riverblades",
    "weapons": [
      {
        "attacks": 4,
        "dmg_crit": 5,
        "dmg_hit": 2,
        "max_range": 2,
        "min_range": 0,
        "runemark": "spear",
        "strength": 5
      }
    ],
    "wounds": 18
  },
  {
    "_id": "6e9c2283",
    "bladeborn": "",
    "grand_alliance": "order",
    "movement": 5,
    "name": "Pureflood Seneschal with Master's Blades",
    "points": 210,
    "runemarks": ["elite", "hero"],
    "toughness": 4,
    "warband": "Ydrilan Riverblades",
    "weapons": [
      {
        "attacks": 5,
        "dmg_crit": 4,
        "dmg_hit": 3,
        "max_range": 1,
        "min_range": 0,
        "runemark": "sword",
        "strength": 4
      }
    ],
    "wounds": 18
  },
  {
    "_id": "67c44120",
    "bladeborn": "",
    "grand_alliance": "order",
    "movement": 5,
    "name": "Pureflood Seneschal with Ythara Darts",
    "points": 210,
    "runemarks": ["elite", "hero"],
    "toughness": 4,
    "warband": "Ydrilan Riverblades",
    "weapons": [
      {
        "attacks": 4,
        "dmg_crit": 3,
        "dmg_hit": 2,
        "max_range": 8,
        "min_range": 0,
        "runemark": "ranged",
        "strength": 4
      }
    ],
    "wounds": 18
  },
  {
    "_id": "b2937bc4",
    "bladeborn": "",
    "grand_alliance": "order",
    "movement": 5,
    "name": "Crestdancer with Twin-spear",
    "points": 115,
    "runemarks": ["elite"],
    "toughness": 4,
    "warband": "Ydrilan Riverblades",
    "weapons": [
      {
        "attacks": 3,
        "dmg_crit": 4,
        "dmg_hit": 2,
        "max_range": 2,
        "min_range": 0,
        "runemark": "spear",
        "strength": 4
      }
    ],
    "wounds": 10
  },
  {
    "_id": "6e2639f6",
    "bladeborn": "",
    "grand_alliance": "order",
    "movement": 5,
    "name": "Crestdancer with Roped Sickle",
    "points": 115,
    "runemarks": ["elite"],
    "toughness": 4,
    "warband": "Ydrilan Riverblades",
    "weapons": [
      {
        "attacks": 4,
        "dmg_crit": 4,
        "dmg_hit": 1,
        "max_range": 3,
        "min_range": 0,
        "runemark": "reach",
        "strength": 4
      }
    ],
    "wounds": 10
  },
  {
    "_id": "3d77dca0",
    "bladeborn": "",
    "grand_alliance": "order",
    "movement": 5,
    "name": "Stream-runner with Crestblades",
    "points": 65,
    "runemarks": ["agile"],
    "toughness": 3,
    "warband": "Ydrilan Riverblades",
    "weapons": [
      {
        "attacks": 4,
        "dmg_crit": 2,
        "dmg_hit": 1,
        "max_range": 1,
        "min_range": 0,
        "runemark": "axe",
        "strength": 3
      }
    ],
    "wounds": 8
  },
  {
    "_id": "217c9ace",
    "bladeborn": "",
    "grand_alliance": "order",
    "movement": 5,
    "name": "Stream-runner with Riversteel Weapons",
    "points": 65,
    "runemarks": [],
    "toughness": 3,
    "warband": "Ydrilan Riverblades",
    "weapons": [
      {
        "attacks": 3,
        "dmg_crit": 3,
        "dmg_hit": 1,
        "max_range": 1,
        "min_range": 0,
        "runemark": "sword",
        "strength": 3
      }
    ],
    "wounds": 8
  }
]

=== krisling049/warcry_data/data/Order/vulkyn_flameseekers.json
[
    {
        "_id": "64ee2181",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 0,
        "name": "TBC Fyreslayers 2",
        "points": 0,
        "runemarks": [],
        "toughness": 0,
        "warband": "Vulkyn Flameseekers",
        "weapons": [
            {
                "attacks": 0,
                "dmg_crit": 0,
                "dmg_hit": 0,
                "max_range": 0,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 0
            }
        ],
        "wounds": 0
    },
    {
        "_id": "a9d356ed",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 0,
        "name": "TBC Fyreslayers 3",
        "points": 0,
        "runemarks": [],
        "toughness": 0,
        "warband": "Vulkyn Flameseekers",
        "weapons": [
            {
                "attacks": 0,
                "dmg_crit": 0,
                "dmg_hit": 0,
                "max_range": 0,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 0
            }
        ],
        "wounds": 0
    },
    {
        "_id": "22956036",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 0,
        "name": "TBC Fyreslayers 4",
        "points": 0,
        "runemarks": [],
        "toughness": 0,
        "warband": "Vulkyn Flameseekers",
        "weapons": [
            {
                "attacks": 0,
                "dmg_crit": 0,
                "dmg_hit": 0,
                "max_range": 0,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 0
            }
        ],
        "wounds": 0
    },
    {
        "_id": "8770f3ac",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 0,
        "name": "TBC Fyreslayers 5",
        "points": 0,
        "runemarks": [],
        "toughness": 0,
        "warband": "Vulkyn Flameseekers",
        "weapons": [
            {
                "attacks": 0,
                "dmg_crit": 0,
                "dmg_hit": 0,
                "max_range": 0,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 0
            }
        ],
        "wounds": 0
    },
    {
        "_id": "56748d38",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 0,
        "name": "TBC Fyreslayers 6",
        "points": 0,
        "runemarks": [],
        "toughness": 0,
        "warband": "Vulkyn Flameseekers",
        "weapons": [
            {
                "attacks": 0,
                "dmg_crit": 0,
                "dmg_hit": 0,
                "max_range": 0,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 0
            }
        ],
        "wounds": 0
    },
    {
        "_id": "df9fe661",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 0,
        "name": "TBC Fyreslayers 7",
        "points": 0,
        "runemarks": [],
        "toughness": 0,
        "warband": "Vulkyn Flameseekers",
        "weapons": [
            {
                "attacks": 0,
                "dmg_crit": 0,
                "dmg_hit": 0,
                "max_range": 0,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 0
            }
        ],
        "wounds": 0
    },
    {
        "_id": "e00e73d1",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 0,
        "name": "TBC Fyreslayers 8",
        "points": 0,
        "runemarks": [],
        "toughness": 0,
        "warband": "Vulkyn Flameseekers",
        "weapons": [
            {
                "attacks": 0,
                "dmg_crit": 0,
                "dmg_hit": 0,
                "max_range": 0,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 0
            }
        ],
        "wounds": 0
    },
    {
        "_id": "vulkyn-1",
        "bladeborn": "",
        "grand_alliance": "order",
        "movement": 3,
        "name": "Scalebreaker",
        "points": 95,
        "runemarks": [
            "elite"
        ],
        "toughness": 4,
        "warband": "Vulkyn Flameseekers",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "wounds": 12
    }
]

=== krisling049/warcry_data/data/Destruction/destruction_thrall.json
[
    {
        "_id": "b7da3ff4",
        "bladeborn": "",
        "grand_alliance": "destruction",
        "movement": 4,
        "name": "Fellwater Troggoth",
        "points": 175,
        "runemarks": [
            "thrall",
            "trapper",
            "bulwark"
        ],
        "toughness": 4,
        "warband": "destruction_thrall",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 5
            }
        ],
        "wounds": 28
    },
    {
        "_id": "a47621f5",
        "bladeborn": "",
        "grand_alliance": "destruction",
        "movement": 4,
        "name": "Rockgut Troggoth",
        "points": 185,
        "runemarks": [
            "thrall",
            "bulwark"
        ],
        "toughness": 5,
        "warband": "destruction_thrall",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 6,
                "dmg_hit": 3,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 5
            }
        ],
        "wounds": 28
    }
]

=== krisling049/warcry_data/data/Death/teratic_cohort_fighters.json
[
    {
        "_id": "0kvxvl2d",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 7,
        "name": "Kavalos Centari",
        "points": 110,
        "runemarks": ["hero", "elite", "mounted"],
        "toughness": 4,
        "warband": "Teratic Cohort",
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            }
        ],
        "wounds": 20
    },
    {
        "_id": "yofte4ap",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 4,
        "name": "Mortek Cykloptian with Dread Glaive",
        "points": 110,
        "runemarks": ["elite"],
        "toughness": 4,
        "warband": "Teratic Cohort",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            }
        ],
        "wounds": 18
    },
    {
        "_id": "6ebtzcs3",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 4,
        "name": "Mortek Cykloptian with Nadirite Bident",
        "points": 145,
        "runemarks": ["elite"],
        "toughness": 4,
        "warband": "Teratic Cohort",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 5
            }
        ],
        "wounds": 18
    },
    {
        "_id": "mg5be1qt",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 4,
        "name": "Teratic Prowler",
        "points": 80,
        "runemarks": ["beast"],
        "toughness": 4,
        "warband": "Teratic Cohort",
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 3
            }
        ],
        "wounds": 10
    },
    {
        "_id": "nqyjc38a",
        "bladeborn": "",
        "grand_alliance": "death",
        "movement": 5,
        "name": "Aviarch Harpy",
        "points": 110,
        "runemarks": ["beast", "fly"],
        "toughness": 4,
        "warband": "Teratic Cohort",
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 4
            }
        ],
        "wounds": 115
    }
]
